"use client";
import { useCallback, useEffect, useState } from "react";

type Player={id:string;email:string;displayName:string;role:string;status:string;createdAt:string;lastLoginAt:string|null;channels:string[];save:{kingdomName:string;updatedAt:string}|null};
type Channel={id:string;name:string;slug:string;status:string;speed:number;durationDays:number;maxPlayers:number;playerCount:number;startsAt:string;endsAt:string|null};

export default function AdminPage(){
 const[data,setData]=useState<{players:Player[];channels:Channel[]}|null>(null),[error,setError]=useState(""),[name,setName]=useState(""),[speed,setSpeed]=useState(1),[days,setDays]=useState(84),[maxPlayers,setMaxPlayers]=useState(300),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const response=await fetch("/api/admin",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Panel açılamadı");setData(body)},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
 async function toggle(type:"player"|"channel",id:string,status:string){setBusy(true);setError("");try{const response=await fetch("/api/admin",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type,id,status:status==="active"?"inactive":"active"})});const body=await response.json();if(!response.ok)throw new Error(body.error);await load()}catch(e){setError(e instanceof Error?e.message:"İşlem başarısız")}finally{setBusy(false)}}
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,speed,durationDays:days,maxPlayers})});const body=await response.json();if(!response.ok)throw new Error(body.error);setName("");await load()}catch(e){setError(e instanceof Error?e.message:"Channel oluşturulamadı")}finally{setBusy(false)}}
 return <main className="admin-shell"><header><div><span>DEMİRKALE</span><h1>Yönetim Divanı</h1></div><a href="/">OYUNA DÖN</a></header>{error&&<div className="admin-error">{error}</div>}{!data&&!error&&<div className="admin-loading">KAYITLAR AÇILIYOR…</div>}{data&&<><section className="admin-stats"><div><span>OYUNCU</span><b>{data.players.length}</b></div><div><span>AKTİF CHANNEL</span><b>{data.channels.filter(x=>x.status==="active").length}</b></div><div><span>KRALLIK</span><b>{data.players.filter(x=>x.save).length}</b></div></section><section className="admin-grid"><article className="admin-card"><div className="admin-card-head"><div><span>CHANNEL YÖNETİMİ</span><h2>Sezonlar</h2></div></div><form className="channel-create" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Yeni channel adı" required minLength={3}/><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>×1 Standart</option><option value={4}>×4 Hızlı</option><option value={24}>×24 Çok hızlı</option></select><label>Süre<input type="number" min="1" max="365" value={days} onChange={e=>setDays(Number(e.target.value))}/><small>gün</small></label><label>Kapasite<input type="number" min="2" max="10000" value={maxPlayers} onChange={e=>setMaxPlayers(Number(e.target.value))}/></label><button disabled={busy}>CHANNEL AÇ</button></form><div className="admin-table-wrap"><table><thead><tr><th>Channel</th><th>Tempo</th><th>Oyuncu</th><th>Süre</th><th>Durum</th></tr></thead><tbody>{data.channels.map(channel=><tr key={channel.id}><td><b>{channel.name}</b><small>{channel.slug}</small></td><td>×{channel.speed}</td><td>{channel.playerCount}/{channel.maxPlayers}</td><td>{channel.durationDays} gün</td><td><button className={channel.status} disabled={busy} onClick={()=>toggle("channel",channel.id,channel.status)}>{channel.status==="active"?"AKTİF":"PASİF"}</button></td></tr>)}</tbody></table></div></article><article className="admin-card wide"><div className="admin-card-head"><div><span>ÜYELER</span><h2>Oyuncular ve krallıklar</h2></div></div><div className="admin-table-wrap"><table><thead><tr><th>Oyuncu</th><th>Krallık</th><th>Channel</th><th>Son giriş</th><th>Yetki</th><th>Durum</th></tr></thead><tbody>{data.players.map(player=><tr key={player.id}><td><b>{player.displayName}</b><small>{player.email}</small></td><td>{player.save?.kingdomName||"Henüz yok"}</td><td>{player.channels.join(", ")||"—"}</td><td>{player.lastLoginAt?new Date(player.lastLoginAt).toLocaleString("tr-TR"):"—"}</td><td>{player.role.toLocaleUpperCase("tr")}</td><td><button className={player.status} disabled={busy||player.role==="admin"} onClick={()=>toggle("player",player.id,player.status)}>{player.status==="active"?"AKTİF":"PASİF"}</button></td></tr>)}</tbody></table></div></article></section></>}</main>
}
