BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE channel_status AS ENUM ('scheduled','active','completed','archived');
CREATE TYPE kingdom_status AS ENUM ('active','conquered','spectator','refugee');
CREATE TYPE terrain_type AS ENUM ('plain','forest','mountain','riverbank','pass','arid');
CREATE TYPE resource_type AS ENUM ('gold','food','stone','wood','iron','ale','wheat','flour','bread','apples','hops','milk','cheese','ore','weapons');
CREATE TYPE action_status AS ENUM ('queued','running','completed','failed','cancelled');
CREATE TYPE army_intent AS ENUM ('attack','reinforce','scout','raid');
CREATE TYPE relation_status AS ENUM ('proposed','active','breached','completed','cancelled');

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_profiles (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, titles jsonb NOT NULL DEFAULT '[]', total_channels_won int NOT NULL DEFAULT 0, highest_population_ever int NOT NULL DEFAULT 0, total_kingdoms_conquered int NOT NULL DEFAULT 0);
CREATE TABLE alliances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, channel_id uuid, secret_objective text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE channels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, channel_type text NOT NULL DEFAULT 'standard', rule_set_version text NOT NULL DEFAULT '2026.1', duration_days int NOT NULL CHECK(duration_days > 0), protection_days int NOT NULL DEFAULT 4 CHECK(protection_days BETWEEN 3 AND 5), max_players int NOT NULL DEFAULT 300, llm_restriction jsonb NOT NULL DEFAULT '{}', starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, status channel_status NOT NULL DEFAULT 'scheduled', winner_alliance_id uuid REFERENCES alliances(id), CHECK(ends_at > starts_at));
ALTER TABLE alliances ADD CONSTRAINT alliances_channel_fk FOREIGN KEY(channel_id) REFERENCES channels(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX alliances_name_channel_idx ON alliances(channel_id, lower(name));

CREATE TABLE map_tiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE, x int NOT NULL, y int NOT NULL, terrain terrain_type NOT NULL, owner_kingdom_id uuid, is_capital boolean NOT NULL DEFAULT false, base_yield jsonb NOT NULL DEFAULT '{}', mine_reserve_remaining numeric(16,3) NOT NULL DEFAULT 0, mine_reserve_original numeric(16,3) NOT NULL DEFAULT 0, deep_dig_count int NOT NULL DEFAULT 0, UNIQUE(channel_id,x,y));
CREATE TABLE kingdoms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE, name text NOT NULL, capital_tile_id uuid REFERENCES map_tiles(id), alliance_id uuid REFERENCES alliances(id) ON DELETE SET NULL, vassal_of_kingdom_id uuid, status kingdom_status NOT NULL DEFAULT 'active', resources jsonb NOT NULL DEFAULT '{"gold":1000,"food":500,"stone":300,"wood":300,"iron":100,"ale":0}', population numeric(12,3) NOT NULL DEFAULT 100, population_capacity int NOT NULL DEFAULT 150, popularity numeric(5,2) NOT NULL DEFAULT 50 CHECK(popularity BETWEEN 0 AND 100), reputation numeric(5,2) NOT NULL DEFAULT 50 CHECK(reputation BETWEEN 0 AND 100), general_loyalty numeric(5,2) NOT NULL DEFAULT 75 CHECK(general_loyalty BETWEEN 0 AND 100), tax_rate int NOT NULL DEFAULT 15 CHECK(tax_rate BETWEEN 0 AND 100), strategy_note text NOT NULL DEFAULT 'Ekonomiyi büyüt, savunmada kal.', protection_ends_at timestamptz NOT NULL, decree_quota_remaining int NOT NULL DEFAULT 2, decree_quota_last_refill_at timestamptz NOT NULL DEFAULT now(), last_resource_tick_at timestamptz NOT NULL DEFAULT now(), last_active_at timestamptz, last_passive_llm_at timestamptz, api_key_ciphertext bytea, api_key_iv bytea, api_key_tag bytea, api_key_key_version text, llm_provider text, llm_model text, llm_muted boolean NOT NULL DEFAULT true, conquered_by_kingdom_id uuid REFERENCES kingdoms(id), UNIQUE(channel_id,user_id), UNIQUE(channel_id,name));
ALTER TABLE map_tiles ADD CONSTRAINT map_tiles_owner_fk FOREIGN KEY(owner_kingdom_id) REFERENCES kingdoms(id) ON DELETE SET NULL;
ALTER TABLE kingdoms ADD CONSTRAINT kingdoms_vassal_fk FOREIGN KEY(vassal_of_kingdom_id) REFERENCES kingdoms(id) ON DELETE SET NULL;

CREATE TABLE building_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, tile_id uuid REFERENCES map_tiles(id), type text NOT NULL, level int NOT NULL DEFAULT 1 CHECK(level BETWEEN 0 AND 20), target_level int, upgrade_started_at timestamptz, upgrade_completes_at timestamptz, condition numeric(5,2) NOT NULL DEFAULT 100, UNIQUE(kingdom_id,type,tile_id));
CREATE INDEX building_due_idx ON building_instances(upgrade_completes_at) WHERE upgrade_completes_at IS NOT NULL;
CREATE TABLE unit_stocks (kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, unit_type text NOT NULL, count int NOT NULL DEFAULT 0 CHECK(count >= 0), rented_out int NOT NULL DEFAULT 0 CHECK(rented_out >= 0), PRIMARY KEY(kingdom_id,unit_type));
CREATE TABLE training_queue (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, unit_type text NOT NULL, count int NOT NULL CHECK(count > 0), population_reserved int NOT NULL DEFAULT 0, completes_at timestamptz NOT NULL, status action_status NOT NULL DEFAULT 'queued', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX training_due_idx ON training_queue(completes_at) WHERE status='queued';
CREATE TABLE armies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, composition jsonb NOT NULL, origin_tile_id uuid NOT NULL REFERENCES map_tiles(id), target_tile_id uuid NOT NULL REFERENCES map_tiles(id), departs_at timestamptz NOT NULL, arrives_at timestamptz NOT NULL, intent army_intent NOT NULL, tactic text NOT NULL DEFAULT 'front', fatigue_factor numeric(5,3) NOT NULL DEFAULT 1, supplies numeric(14,3) NOT NULL DEFAULT 0, status action_status NOT NULL DEFAULT 'running');
CREATE INDEX army_due_idx ON armies(arrives_at) WHERE status='running';
CREATE TABLE sieges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), army_id uuid NOT NULL REFERENCES armies(id), target_tile_id uuid NOT NULL REFERENCES map_tiles(id), defender_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), started_at timestamptz NOT NULL DEFAULT now(), next_round_at timestamptz NOT NULL, current_round int NOT NULL DEFAULT 0, wall_integrity numeric(5,2) NOT NULL DEFAULT 100, attacker_morale numeric(5,3) NOT NULL DEFAULT 1, defender_morale numeric(5,3) NOT NULL DEFAULT 1, status action_status NOT NULL DEFAULT 'running');
CREATE TABLE battle_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), channel_id uuid NOT NULL REFERENCES channels(id), attacker_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), defender_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), siege_id uuid REFERENCES sieges(id), intent army_intent NOT NULL, outcome jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE caravans (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id), origin_tile_id uuid NOT NULL REFERENCES map_tiles(id), target_tile_id uuid NOT NULL REFERENCES map_tiles(id), resource resource_type NOT NULL, amount numeric(14,3) NOT NULL CHECK(amount > 0 AND amount <= 200), departs_at timestamptz NOT NULL, arrives_at timestamptz NOT NULL, status action_status NOT NULL DEFAULT 'running', purpose text NOT NULL DEFAULT 'loot');
CREATE INDEX caravan_due_idx ON caravans(arrives_at) WHERE status='running';

CREATE TABLE pending_decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, risk_tier text NOT NULL CHECK(risk_tier IN ('routine','major','catastrophic')), proposed_action jsonb NOT NULL, general_recommendation text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, status relation_status NOT NULL DEFAULT 'proposed');
CREATE TABLE command_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id), nonce text NOT NULL, source text NOT NULL CHECK(source IN ('king','passive_general','diplomacy','system')), tool_name text NOT NULL, arguments jsonb NOT NULL, result jsonb, decree_cost int NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(kingdom_id,nonce));
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id) ON DELETE CASCADE, category text NOT NULL, title text NOT NULL, body text NOT NULL, data jsonb NOT NULL DEFAULT '{}', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE diplomacy_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), from_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), to_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), proposal_type text NOT NULL, content text NOT NULL, transcript_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE protection_relationships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), protector_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), vassal_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), tribute_resource resource_type NOT NULL DEFAULT 'gold', tribute_rate numeric(8,4) NOT NULL, next_tribute_at timestamptz NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), status relation_status NOT NULL DEFAULT 'proposed', UNIQUE(protector_kingdom_id,vassal_kingdom_id));
CREATE TABLE troop_rentals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lender_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), borrower_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), unit_type text NOT NULL, count int NOT NULL CHECK(count > 0), fee_gold numeric(14,3) NOT NULL CHECK(fee_gold >= 0), started_at timestamptz, ends_at timestamptz, status relation_status NOT NULL DEFAULT 'proposed');
CREATE TABLE market_offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id), offer_resource resource_type NOT NULL, offer_amount numeric(14,3) NOT NULL CHECK(offer_amount > 0), request_resource resource_type NOT NULL, request_amount numeric(14,3) NOT NULL CHECK(request_amount > 0), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, accepted_by_kingdom_id uuid REFERENCES kingdoms(id), status relation_status NOT NULL DEFAULT 'proposed', CHECK(offer_resource <> request_resource));
CREATE TABLE trade_agreements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_a_id uuid NOT NULL REFERENCES kingdoms(id), kingdom_b_id uuid NOT NULL REFERENCES kingdoms(id), resource_a resource_type NOT NULL, amount_a numeric(14,3) NOT NULL, resource_b resource_type NOT NULL, amount_b numeric(14,3) NOT NULL, frequency interval NOT NULL DEFAULT interval '1 day', next_exchange_at timestamptz NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), status relation_status NOT NULL DEFAULT 'proposed');
CREATE TABLE spies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id), target_kingdom_id uuid NOT NULL REFERENCES kingdoms(id), mission text NOT NULL CHECK(mission IN ('gather_intel','sabotage','counter_intel')), arrives_at timestamptz NOT NULL, status action_status NOT NULL DEFAULT 'running', outcome jsonb);
CREATE TABLE world_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE, type text NOT NULL CHECK(type IN ('bountiful_harvest','plague','bandit_raid','traveling_merchant','rebellion')), affected_kingdom_id uuid REFERENCES kingdoms(id), region_id text, triggered_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, effect jsonb NOT NULL);
CREATE TABLE regional_bulletins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kingdom_id uuid NOT NULL REFERENCES kingdoms(id), summary text NOT NULL, event_ids jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE season_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), channel_id uuid NOT NULL REFERENCES channels(id), kingdom_id uuid REFERENCES kingdoms(id), alliance_id uuid REFERENCES alliances(id), rank int NOT NULL, population_peak int NOT NULL DEFAULT 0, tiles_conquered int NOT NULL DEFAULT 0, survived_until timestamptz NOT NULL, archived_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX kingdoms_channel_status_idx ON kingdoms(channel_id,status); CREATE INDEX notifications_unread_idx ON notifications(kingdom_id,created_at) WHERE read_at IS NULL; CREATE INDEX decisions_open_idx ON pending_decisions(kingdom_id,expires_at) WHERE status='proposed';
COMMIT;
