"use client";
import { useState } from "react";

export type Account={id:string;email:string;displayName:string;role:"player"|"admin";status:string};

async function readAuthResponse(response:Response){
 const text=await response.text();
 if(!text)return {} as {user?:Account;error?:string};
 try{return JSON.parse(text) as {user?:Account;error?:string}}
 catch{return {error:response.ok?"Sunucudan geçersiz bir yanıt alındı.":"Sunucu geçici olarak yanıt veremedi. Lütfen tekrar deneyin."}}
}

export default function AccountGate({onAuthenticated}:{onAuthenticated:(user:Account)=>void}){
 const[mode,setMode]=useState<"login"|"register">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[displayName,setDisplayName]=useState(""),[adminInvite,setAdminInvite]=useState(""),[showAdmin,setShowAdmin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:mode,email,password,displayName,adminInvite})});const data=await readAuthResponse(response);if(!response.ok||!data.user)throw new Error(data.error||"Oturum açılamadı.");onAuthenticated(data.user)}catch(e){setError(e instanceof Error?e.message:"Oturum açılamadı.")}finally{setBusy(false)}}
 return <main className="account-gate"><div className="account-landscape"><i/><i/><i/></div><header><div className="brand-mark">♜</div><div className="title-block"><h1>DEMİRKALE</h1><p>KALICI KRALLIK DÜNYASI</p></div></header><section className="account-card"><p className="eyebrow">{mode==="login"?"TAHTINA DÖN":"YENİ BİR HANEDAN"}</p><h2>{mode==="login"?"Krallığına giriş yap":"Oyuncu hesabını kur"}</h2><p>{mode==="login"?"Başka bir cihazda bıraktığın krallık aynı hesapla burada devam eder.":"E-posta doğrulaması gerekmez. Hesabın açılır açılmaz ilk channel'ını seçebilirsin."}</p><div className="account-tabs"><button className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("")}}>GİRİŞ</button><button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setError("")}}>KAYIT OL</button></div><form onSubmit={submit}>{mode==="register"&&<label>Oyuncu adı<input value={displayName} onChange={e=>setDisplayName(e.target.value)} minLength={2} maxLength={40} required autoComplete="nickname"/></label>}<label>E-posta<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Şifre<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete={mode==="login"?"current-password":"new-password"}/></label>{mode==="register"&&<><button type="button" className="admin-invite-toggle" onClick={()=>setShowAdmin(x=>!x)}>{showAdmin?"Yönetici kodunu gizle":"Yönetici davet kodum var"}</button>{showAdmin&&<label>Yönetici davet kodu<input value={adminInvite} onChange={e=>setAdminInvite(e.target.value)} autoComplete="off"/></label>}</>}{error&&<div className="account-error">{error}</div>}<button className="primary-seal account-submit" disabled={busy}>{busy?"MÜHÜR KONTROL EDİLİYOR…":mode==="login"?"TAHTA DÖN":"HESABI OLUŞTUR"}</button></form><small>Şifren güvenli biçimde özetlenir; düz metin olarak saklanmaz.</small></section></main>
}
