"use client";
import { useEffect, useMemo, useState } from "react";
import KingdomScene from "./KingdomScene";

type Key="gold"|"food"|"stone"|"wood"|"iron"|"ale"; type Res=Record<Key,number>;
type Building={type:string;name:string;category:string;level:number}; type Queue={kind:"building"|"unit";type:string;name:string;targetLevel?:number;count?:number;completesAt:number};
type Notice={kind:string;text:string;at:number}; type Tab="meclis"|"binalar"|"ordu"|"defter"|"diyar"; type Setup="welcome"|"channel"|"kingdom"|"general";
type Game={version:2;kingdomName:string;rulerName:string;channel:string;speed:number;terrain:string;foundedAt:number;lastTickAt:number;protectionEndsAt:number;resources:Res;population:number;capacity:number;popularity:number;reputation:number;loyalty:number;taxRate:number;quota:number;quotaAt:number;buildings:Building[];units:Record<string,number>;queue:Queue|null;notices:Notice[];provider:string|null;model:string|null;generalConnected:boolean};
const STORE="demirkale.game.v2";
const modelOptions={
 openai:[{id:"gpt-5.6-terra",label:"GPT-5.6 Terra — Dengeli (önerilen)"},{id:"gpt-5.6-sol",label:"GPT-5.6 Sol — En güçlü"},{id:"gpt-5.6-luna",label:"GPT-5.6 Luna — Hızlı ve ekonomik"},{id:"gpt-5.5",label:"GPT-5.5 — Güçlü"},{id:"gpt-5.4-mini",label:"GPT-5.4 mini — Ekonomik"}],
 anthropic:[{id:"claude-sonnet-5",label:"Claude Sonnet 5 — Dengeli (önerilen)"},{id:"claude-opus-5",label:"Claude Opus 5 — En güçlü"},{id:"claude-fable-5",label:"Claude Fable 5 — Uzun görevler"},{id:"claude-haiku-4-5",label:"Claude Haiku 4.5 — Hızlı ve ekonomik"}]
} as const;
const channels=[{id:"standard",name:"Standart Sezon III",detail:"84 gün · Açık modeller · 124/300 Kral",speed:1,remaining:"83 gün"},{id:"frontier",name:"Sınır Boyu",detail:"28 gün · ×4 tempo · 41/120 Kral",speed:4,remaining:"27 gün"},{id:"rapid",name:"Hızlı Taç",detail:"7 gün · ×24 tempo · 18/80 Kral",speed:24,remaining:"6 gün"}];
const catalog=[
 {type:"wheat_farm",name:"Buğday Tarlası",category:"Ekonomi",unlock:1,seconds:3600,cost:{wood:80},detail:"+18 yiyecek/sa"},{type:"lumberjack",name:"Oduncu Kulübesi",category:"Ekonomi",unlock:1,seconds:3600,cost:{gold:40,stone:25},detail:"+22 odun/sa"},{type:"quarry",name:"Taş Ocağı",category:"Ekonomi",unlock:1,seconds:5400,cost:{wood:100,gold:60},detail:"+16 taş/sa"},{type:"town_square",name:"Meydan",category:"Yönetim",unlock:1,seconds:7200,cost:{wood:120,stone:80},detail:"+80 nüfus kapasitesi"},{type:"barracks",name:"Kışla",category:"Askerî",unlock:1,seconds:9000,cost:{wood:170,stone:140},detail:"Temel birlikleri açar"},{type:"apple_orchard",name:"Elma Bahçesi",category:"Ekonomi",unlock:1,seconds:4200,cost:{wood:90,gold:30},detail:"+10 yiyecek/sa"},{type:"mill",name:"Değirmen",category:"Ekonomi",unlock:2,seconds:10800,cost:{wood:100,stone:120},detail:"Buğday zincirini büyütür"},{type:"market",name:"Pazar",category:"Ekonomi",unlock:2,seconds:14400,cost:{wood:160,stone:80},detail:"3 açık teklif yuvası"},{type:"wall",name:"Sur",category:"Askerî",unlock:3,seconds:28800,cost:{stone:500,wood:100},detail:"+%20 savunma"},{type:"mine",name:"Maden",category:"Ekonomi",unlock:1,seconds:10800,cost:{wood:150,stone:80},detail:"50.000 cevher rezervi"}
] as const;
const meta:Array<[Key,string]>=[["gold","ALTIN"],["food","YİYECEK"],["stone","TAŞ"],["wood","ODUN"],["iron","DEMİR"],["ale","BİRA"]];
const fmt=(n:number)=>new Intl.NumberFormat("tr-TR").format(Math.max(0,Math.round(n))); const keep=(g:Game)=>g.buildings.find(b=>b.type==="keep")?.level??1; const qph=(l:number)=>l>=5?4:l>=3?3:2;
const affordable=(r:Res,c:Partial<Res>)=>Object.entries(c).every(([k,v])=>r[k as Key]>=(v??0)); const costFor=(base:Partial<Res>,level:number)=>Object.fromEntries(Object.entries(base).map(([k,v])=>[k,Math.ceil((v??0)*Math.pow(1.65,level))])) as Partial<Res>;
const left=(at:number,now:number)=>{const s=Math.max(0,Math.ceil((at-now)/1000));return s>=3600?`${Math.floor(s/3600)}sa ${Math.floor(s%3600/60)}dk`:s>=60?`${Math.floor(s/60)}dk ${s%60}sn`:`${s}sn`};
function rates(g:Game):Res{const l=Object.fromEntries(g.buildings.map(b=>[b.type,b.level]));return{gold:g.population*g.taxRate/100*.22,food:(l.wheat_farm??0)*18+(l.apple_orchard??0)*10-g.population*.035,stone:(l.quarry??0)*16,wood:(l.lumberjack??0)*22,iron:(l.mine??0)*7,ale:0}}
function tick(g:Game,now:number):Game{const h=Math.min(24,(now-g.lastTickAt)/3_600_000*g.speed);if(h<=0)return g;const rt=rates(g),resources={...g.resources};meta.forEach(([k])=>resources[k]=Math.max(0,resources[k]+rt[k]*h));let buildings=g.buildings,units=g.units,queue=g.queue,notices=g.notices;if(queue&&queue.completesAt<=now){if(queue.kind==="building"){const old=buildings.find(b=>b.type===queue!.type),item=catalog.find(b=>b.type===queue!.type);buildings=old?buildings.map(b=>b.type===queue!.type?{...b,level:queue!.targetLevel!}:b):[...buildings,{type:queue.type,name:queue.name.replace(/ Sv\.\d+$/,"")||item?.name||queue.name,category:item?.category??"Yönetim",level:queue.targetLevel??1}]}else units={...units,[queue.type]:(units[queue.type]??0)+(queue.count??0)};notices=[{kind:"TAMAMLANDI",text:`${queue.name} tamamlandı.`,at:now},...notices].slice(0,20);queue=null}const lv=keep({...g,buildings}),sq=buildings.find(b=>b.type==="town_square")?.level??0,capacity=150+sq*80+(lv-1)*50;const popularity=Math.max(0,Math.min(100,g.popularity+((15-g.taxRate)*.025+(rt.food>=0?.06:-.18))*h));const growth=popularity>=50&&rt.food>=0?( .08+sq*.04)*h:popularity<20?-.2*h:0;const qHours=Math.floor((now-g.quotaAt)/3_600_000);return{...g,resources,popularity,population:Math.max(20,Math.min(capacity,g.population+growth)),capacity,buildings,units,queue,notices,quota:Math.min(qph(lv)*2,g.quota+qHours*qph(lv)),quotaAt:qHours?g.quotaAt+qHours*3_600_000:g.quotaAt,lastTickAt:now}}

export default function KingdomGame(){
 const[ready,setReady]=useState(false),[setup,setSetup]=useState<Setup>("welcome"),[selected,setSelected]=useState(channels[2]);const[name,setName]=useState(""),[ruler,setRuler]=useState(""),[terrain,setTerrain]=useState("plain"),[provider,setProvider]=useState<keyof typeof modelOptions>("openai"),[model,setModel]=useState("gpt-5.6-terra"),[apiKey,setApiKey]=useState("");
 const[game,setGame]=useState<Game|null>(null),[now,setNow]=useState(Date.now()),[tab,setTab]=useState<Tab>("meclis"),[night,setNight]=useState(false),[message,setMessage]=useState(""),[chat,setChat]=useState<Array<{who:string;text:string}>>([]),[toast,setToast]=useState(""),[connecting,setConnecting]=useState(false),[generalError,setGeneralError]=useState(""),[showConnect,setShowConnect]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem(STORE);if(saved)try{const restored=tick(JSON.parse(saved),Date.now());setGame({...restored,generalConnected:false})}catch{localStorage.removeItem(STORE)}setReady(true)},[]);
 useEffect(()=>{const id=setInterval(()=>{const n=Date.now();setNow(n);setGame(g=>g?tick(g,n):null)},1000);return()=>clearInterval(id)},[]);useEffect(()=>{if(game&&ready)localStorage.setItem(STORE,JSON.stringify(game))},[game,ready]);
 const lv=game?keep(game):1,rt=useMemo(()=>game?rates(game):null,[game]);
 function found(connected:boolean,introduction?:string){const t=Date.now();const g:Game={version:2,kingdomName:name.trim(),rulerName:ruler.trim(),channel:selected.name,speed:selected.speed,terrain,foundedAt:t,lastTickAt:t,protectionEndsAt:t+4*86_400_000,resources:{gold:1000,food:500,stone:300,wood:300,iron:100,ale:0},population:100,capacity:150,popularity:50,reputation:50,loyalty:75,taxRate:15,quota:2,quotaAt:t,buildings:[{type:"keep",name:"Kale",category:"Yönetim",level:1},{type:"wheat_farm",name:"Buğday Tarlası",category:"Ekonomi",level:1},{type:"lumberjack",name:"Oduncu Kulübesi",category:"Ekonomi",level:1}],units:{spearman:0},queue:null,notices:[{kind:"KURULUŞ",text:"Krallığınız dış çeperdeki boş parsele kuruldu. Dört günlük korumanız başladı.",at:t}],provider:connected?provider:null,model:connected?model:null,generalConnected:connected};setGame(g);setChat([{who:connected?"General Aldric":"Saray Kâtibi",text:connected?(introduction||"Bağlantı doğrulandı. İlk hedefinizi belirleyin."):"General henüz sessiz. Üretim ve kuyruklar çalışacak; emirleri yönetim kartlarından mühürleyebilirsiniz."}])}
 function kingdomContext(g:Game|null){return g?{name:g.kingdomName,ruler:g.rulerName,keepLevel:keep(g),population:g.population,popularity:g.popularity,resources:g.resources,buildings:g.buildings.map(b=>({name:b.name,level:b.level})),units:g.units}:{name:name.trim(),ruler:ruler.trim(),keepLevel:1,population:100,popularity:50,resources:{gold:1000,food:500,stone:300,wood:300,iron:100,ale:0},buildings:[{name:"Kale",level:1},{name:"Buğday Tarlası",level:1},{name:"Oduncu Kulübesi",level:1}],units:{spearman:0}}}
 async function askGeneral(mode:"test"|"chat",text?:string){const response=await fetch("/api/general",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,model,apiKey,mode,message:text,kingdom:kingdomContext(game)})});const data=await response.json() as {text?:string;error?:string};if(!response.ok)throw new Error(data.error||"General bağlantısı başarısız oldu.");return data.text||"General bağlantısı doğrulandı."}
 async function connectAndFound(){if(!apiKey.trim())return setGeneralError("API anahtarını girmelisiniz.");setConnecting(true);setGeneralError("");try{const intro=await askGeneral("test");found(true,intro)}catch(error){setGeneralError(error instanceof Error?error.message:"Bağlantı kurulamadı.")}finally{setConnecting(false)}}
 async function reconnectGeneral(){if(!game||!apiKey.trim())return setGeneralError("API anahtarını girmelisiniz.");setConnecting(true);setGeneralError("");try{const intro=await askGeneral("test");setGame({...game,provider,model,generalConnected:true});setChat(x=>[...x,{who:"General Aldric",text:intro}]);setShowConnect(false);setToast("General bağlantısı doğrulandı.")}catch(error){setGeneralError(error instanceof Error?error.message:"Bağlantı kurulamadı.")}finally{setConnecting(false)}}
 function debit(g:Game,c:Partial<Res>){const r={...g.resources};Object.entries(c).forEach(([k,v])=>r[k as Key]-=v??0);return r}
 function build(type:string){if(!game||game.queue)return setToast("Aynı anda yalnızca bir kuyruk çalışabilir.");if(game.quota<1)return setToast("Emir kotanız tükendi.");const item=catalog.find(b=>b.type===type);if(!item)return;const old=game.buildings.find(b=>b.type===type),current=old?.level??0;if(item.unlock>lv)return setToast(`Kale Sv.${item.unlock} gerekli.`);const cost=costFor(item.cost,current);if(!affordable(game.resources,cost))return setToast("Bu yapı için kaynak yetersiz.");setGame({...game,resources:debit(game,cost),quota:game.quota-1,queue:{kind:"building",type,name:`${item.name} Sv.${current+1}`,targetLevel:current+1,completesAt:now+item.seconds/game.speed*1000},notices:[{kind:"EMİR",text:`${item.name} için inşa emri verildi.`,at:now},...game.notices]});setToast("Emir mühürlendi; inşaat başladı.")}
 function upgradeKeep(){if(!game||game.queue||game.quota<1||lv>=6)return setToast(game?.queue?"Önce mevcut kuyruk tamamlanmalı.":"Bu emir şu anda verilemiyor.");const costs:Array<Partial<Res>>=[{},{gold:300,stone:400,wood:250},{gold:700,stone:900,wood:600},{gold:1500,stone:1800,wood:1100},{gold:3500,stone:4000,wood:2500,iron:300},{gold:8000,stone:9000,wood:5000,iron:800}],cost=costs[lv];if(!affordable(game.resources,cost))return setToast("Kale yükseltmesi için kaynak yetersiz.");const seconds=[0,10800,28800,64800,172800,388800][lv];setGame({...game,resources:debit(game,cost),quota:game.quota-1,queue:{kind:"building",type:"keep",name:`Kale Sv.${lv+1}`,targetLevel:lv+1,completesAt:now+seconds/game.speed*1000}})}
 function train(){if(!game||game.queue||game.quota<1)return setToast("Kuyruk veya emir kotası uygun değil.");if(!game.buildings.some(b=>b.type==="barracks"))return setToast("Önce Kışla kurmalısınız.");const c={gold:80,food:100,iron:10};if(!affordable(game.resources,c))return setToast("10 Mızrakçı için kaynak yetersiz.");setGame({...game,resources:debit(game,c),quota:game.quota-1,population:Math.max(20,game.population-10),queue:{kind:"unit",type:"spearman",name:"10 Mızrakçı",count:10,completesAt:now+12000/game.speed*1000}})}
 function festival(){if(!game||game.quota<1)return setToast("Emir kotası yetersiz.");const c={gold:120,food:150};if(!affordable(game.resources,c))return setToast("Şenlik için kaynak yetersiz.");setGame({...game,resources:debit(game,c),quota:game.quota-1,popularity:Math.min(100,game.popularity+12),notices:[{kind:"ŞENLİK",text:"Halk meydanda toplandı; rıza 12 puan yükseldi.",at:now},...game.notices]})}
 async function send(e:React.FormEvent){e.preventDefault();if(!game||!message.trim()||connecting)return;const order=message.trim();setChat(x=>[...x,{who:game.rulerName,text:order}]);setMessage("");if(!game.generalConnected||!apiKey){setChat(x=>[...x,{who:"Saray Kâtibi",text:"General bağlantısı bu oturumda etkin değil. Anahtar güvenlik nedeniyle saklanmadı; yeniden bağlayın."}]);setShowConnect(true);return}setConnecting(true);try{const answer=await askGeneral("chat",order);setChat(x=>[...x,{who:"General Aldric",text:answer}])}catch(error){setChat(x=>[...x,{who:"Saray Kâtibi",text:error instanceof Error?error.message:"General yanıt veremedi."}]);setGame({...game,generalConnected:false});setShowConnect(true)}finally{setConnecting(false)}}
 function reset(){if(confirm("Bu cihazdaki krallık silinsin ve yeniden başlansın mı?")){localStorage.removeItem(STORE);setGame(null);setSetup("welcome")}}
 if(!ready)return <div className="boot-screen">DİYAR HAZIRLANIYOR…</div>;
 if(!game)return <Onboarding step={setup} setStep={setSetup} selected={selected} setSelected={setSelected} name={name} setName={setName} ruler={ruler} setRuler={setRuler} terrain={terrain} setTerrain={setTerrain} provider={provider} setProvider={setProvider} model={model} setModel={setModel} apiKey={apiKey} setApiKey={setApiKey} found={found} connect={connectAndFound} connecting={connecting} error={generalError}/>;
 return <main className={night?"app-shell night":"app-shell"}>{toast&&<button className="toast" onClick={()=>setToast("")}>{toast} ×</button>}{showConnect&&<div className="connect-overlay"><section className="connect-card"><button className="close-connect" onClick={()=>setShowConnect(false)}>×</button><p className="eyebrow">GENERALİ YENİDEN BAĞLA</p><h2>BYOK oturum bağlantısı</h2><div className="form-grid"><label>Sağlayıcı<select value={provider} onChange={e=>{const next=e.target.value as keyof typeof modelOptions;setProvider(next);setModel(modelOptions[next][0].id)}}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}>{modelOptions[provider].map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label><label className="wide">API anahtarı<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off"/></label></div>{generalError&&<div className="connection-error">{generalError}</div>}<p className="privacy-note">Anahtar yalnızca sağlayıcı isteği sırasında kullanılır; tarayıcı deposuna veya oyun kaydına yazılmaz.</p><button className="primary-seal connect-submit" disabled={connecting||!apiKey.trim()} onClick={reconnectGeneral}>{connecting?"DOĞRULANIYOR…":"BAĞLANTIYI DOĞRULA"}</button></section></div>}<header className="topbar"><div className="brand-mark">♜</div><div className="title-block"><h1>{game.kingdomName.toLocaleUpperCase("tr")}</h1><p>KRALLIK SİMÜLASYONU</p></div><div className="channel-chip"><span>● AKTİF</span><b>{game.channel}</b><small>Gün 1 · Koruma {left(game.protectionEndsAt,now)}</small></div><button className="day-toggle" onClick={()=>setNight(x=>!x)}>{night?"☾ GECE":"☀ GÜNDÜZ"}</button><button className="profile-button" onClick={reset}>{game.rulerName} · Sıfırla</button></header>
 <section className="resource-ribbon">{meta.map(([k,label])=><div className="resource" key={k}><span>{label}</span><strong>{fmt(game.resources[k])}</strong><small className={(rt?.[k]??0)<0?"negative":""}>{(rt?.[k]??0)>=0?"+":""}{(rt?.[k]??0).toFixed(1)}/sa</small></div>)}<div className="population"><span>HALKIN RIZASI</span><strong>{Math.round(game.popularity)}</strong><div className="meter"><i style={{width:`${game.popularity}%`}}/></div><small>{Math.round(game.population)} / {game.capacity} nüfus</small></div></section>
 <section className="world-stage"><KingdomScene night={night} keepLevel={lv} developed={lv>=3&&game.buildings.length>=8}/><div className="scene-title"><span>YENİ BAŞKENT · {game.terrain.toLocaleUpperCase("tr")}</span><h2>{game.kingdomName}</h2><p>Kale Sv.{lv} · {game.buildings.length} yapı · {Object.values(game.units).reduce((a,b)=>a+b,0)} asker</p></div>{game.queue&&<div className="active-queue"><span>DEVAM EDİYOR</span><b>{game.queue.name}</b><strong>{left(game.queue.completesAt,now)}</strong></div>}
 <aside className="council-panel"><div className="general-bars">{[["Sadakat",game.loyalty],["Emir Kotası",`${game.quota}/${qph(lv)*2}`],["İtibar",game.reputation]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><div><i style={{width:`${typeof value==="number"?value:game.quota/(qph(lv)*2)*100}%`}}/></div><b>{value}</b></div>)}</div><nav className="tabs five">{(["meclis","binalar","ordu","defter","diyar"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.toLocaleUpperCase("tr")}</button>)}</nav><div className="panel-content">
 {tab==="meclis"&&<div className="council-content"><div className="advisor"><div className="portrait">A</div><div><h3>{game.generalConnected?"General Aldric":"General sessiz"}</h3><p>{game.generalConnected?`${game.provider} · ${game.model}`:"BYOK bağlantısı bekleniyor"}</p></div>{!game.generalConnected&&<button className="reconnect-button" onClick={()=>{setGeneralError("");setShowConnect(true)}}>BAĞLA</button>}<span className={game.generalConnected?"online":"offline"}>●</span></div><div className="first-objective"><span>İLK HEDEF</span><b>Ekonomiyi dengede tut</b><p>Yiyecek üretimini pozitif tutun; ardından Meydan veya Kışla kurun.</p></div><div className="chat-log">{chat.map((x,i)=><div className={x.who===game.rulerName?"message king":"message"} key={i}><b>{x.who}</b><p>{x.text}</p></div>)}{connecting&&<div className="message thinking"><b>GENERAL ALDRIC</b><p>Haritayı ve defterleri inceliyor…</p></div>}</div><form className="chat-form" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Generalinize buyruğunuzu iletin…" disabled={connecting}/><button disabled={connecting}>✦</button></form></div>}
 {tab==="binalar"&&<div className="list-content"><div className="section-head"><span>{game.buildings.length} / {6+(lv-1)*2} YAPI</span><b>{game.queue?.kind==="building"?"1 kuyrukta":"Kuyruk boş"}</b></div><button className="keep-card" onClick={upgradeKeep}><span>♜</span><div><b>Kale Sv.{lv}{lv<6?` → ${lv+1}`:" · Tavan"}</b><small>İdari kapasite ve emir kotası</small></div><strong>{lv<6?"YÜKSELT":"TAMAM"}</strong></button>{catalog.map(item=>{const current=game.buildings.find(b=>b.type===item.type)?.level??0,locked=item.unlock>lv,cost=costFor(item.cost,current);return <button className="build-action" key={item.type} disabled={locked||!!game.queue} onClick={()=>build(item.type)}><span>{item.category}</span><div><b>{item.name} {current?`Sv.${current}`:""}</b><small>{locked?`Kale Sv.${item.unlock} gerekli`:item.detail}</small><em>{Object.entries(cost).map(([k,v])=>`${k} ${v}`).join(" · ")}</em></div><strong>{current?"YÜKSELT":"KUR"}</strong></button>})}</div>}
 {tab==="ordu"&&<div className="army-panel"><div className="section-head"><span>GARNİZON</span><b>{game.units.spearman??0} asker</b></div><div className="empty-army"><span>⚔</span><h3>{game.buildings.some(b=>b.type==="barracks")?"Kışla emir bekliyor":"Henüz Kışlanız yok"}</h3><p>{game.buildings.some(b=>b.type==="barracks")?"10 Mızrakçı: 80 altın · 100 yiyecek · 10 demir":"Asker eğitmek için önce Kışla kurun."}</p>{game.buildings.some(b=>b.type==="barracks")&&<button onClick={train}>10 MIZRAKÇI EĞİT</button>}</div><div className="unit-row"><span>Mızrakçı</span><b>{game.units.spearman??0}</b><small>Savunma 16 · Hız 6</small></div></div>}
 {tab==="defter"&&<div className="ledger"><div className="section-head"><span>HAZİNE VE HALK</span><b>Tick canlı</b></div>{meta.map(([k,label])=><div key={k}><span>{label}</span><strong>{fmt(game.resources[k])}</strong><small className={(rt?.[k]??0)<0?"negative":""}>{(rt?.[k]??0).toFixed(1)}/sa</small></div>)}<div className="tax-control"><label>Vergi oranı <b>%{game.taxRate}</b></label><input type="range" min="0" max="50" value={game.taxRate} onChange={e=>setGame({...game,taxRate:Number(e.target.value)})}/><small>Yüksek vergi altını artırır, halkın rızasını düşürür.</small></div><button className="festival-button" onClick={festival}>ŞENLİK DÜZENLE · 120 ALTIN / 150 YİYECEK</button></div>}
 {tab==="diyar"&&<div className="realm"><div className="section-head"><span>DIŞ ÇEPER · KORUMALI</span><b>{left(game.protectionEndsAt,now)}</b></div><div className="mini-map starter"><i className="you">{game.kingdomName.charAt(0)}</i><span>Merkez krallıkları uzakta<br/>Yeni parseliniz dış halkada</span></div>{game.notices.map((x,i)=><div className="report" key={i}><span>{x.kind}</span><p>{x.text}<small>{new Date(x.at).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})}</small></p></div>)}</div>}
 </div></aside></section></main>
}

function Onboarding(p:{step:Setup;setStep:(s:Setup)=>void;selected:typeof channels[number];setSelected:(c:typeof channels[number])=>void;name:string;setName:(s:string)=>void;ruler:string;setRuler:(s:string)=>void;terrain:string;setTerrain:(s:string)=>void;provider:keyof typeof modelOptions;setProvider:(s:keyof typeof modelOptions)=>void;model:string;setModel:(s:string)=>void;apiKey:string;setApiKey:(s:string)=>void;found:(c:boolean)=>void;connect:()=>void;connecting:boolean;error:string}){return <main className="onboarding"><div className="onboarding-bg"><div className="distant-castle">♜</div></div><header className="onboarding-header"><div className="brand-mark">♜</div><div className="title-block"><h1>DEMİRKALE</h1><p>KRALLIK SİMÜLASYONU</p></div><span>KALICI DÜNYA · BYOK GENERAL</span></header>
 {p.step==="welcome"&&<section className="welcome-card"><p className="eyebrow">TAHT BOŞ · DİYAR SENİ BEKLİYOR</p><h2>Bir krallık miras almayacaksın.<br/><em>Onu sıfırdan kuracaksın.</em></h2><p>Boş bir dış çeper parseli, Kale Sv.1, yüz kişilik bir halk ve sınırlı erzak. Generalinize yön verin; ekonomi, diplomasi ve savaş siz çevrimdışıyken de yaşamaya devam etsin.</p><div className="starting-ledger"><span>1 Kale</span><span>100 Halk</span><span>1.000 Altın</span><span>4 Gün Koruma</span></div><button className="primary-seal" onClick={()=>p.setStep("channel")}>TAHTA DOĞRU İLERLE</button><small>Kayıt bu cihazda tutulur; sıfırlayana kadar devam eder.</small></section>}
 {p.step==="channel"&&<section className="setup-card"><div className="step-count">I / III</div><p className="eyebrow">BİR DÜNYA SEÇ</p><h2>Hangi channel&apos;da hüküm süreceksin?</h2><p>Her channel ayrı bir krallık ve ayrı bir sezondur. İlk oyun için hızlı tempo seçilidir.</p><div className="channel-list">{channels.map(c=><button key={c.id} className={p.selected.id===c.id?"selected":""} onClick={()=>p.setSelected(c)}><i>♜</i><div><b>{c.name}</b><span>{c.detail}</span></div><strong>{c.remaining}</strong></button>)}</div><div className="setup-actions"><button onClick={()=>p.setStep("welcome")}>GERİ</button><button className="primary-seal" onClick={()=>p.setStep("kingdom")}>BU DÜNYAYA KATIL</button></div></section>}
 {p.step==="kingdom"&&<section className="setup-card"><div className="step-count">II / III</div><p className="eyebrow">SANCAĞINI DİK</p><h2>Krallığını kur</h2><div className="form-grid"><label>Hükümdarın adı<input value={p.ruler} onChange={e=>p.setRuler(e.target.value)} placeholder="Örn. Alaric" maxLength={30}/></label><label>Krallığın adı<input value={p.name} onChange={e=>p.setName(e.target.value)} placeholder="Örn. Demirkale" maxLength={36}/></label></div><p className="field-label">Başlangıç arazisi</p><div className="terrain-list">{[["plain","OVA","Dengeli üretim"],["forest","ORMAN","+Odun · +Pusu"],["mountain","DAĞ","+Taş · +Savunma"],["riverbank","NEHİR","+Yiyecek · Yavaş geçiş"]].map(([id,n,d])=><button key={id} className={p.terrain===id?"selected":""} onClick={()=>p.setTerrain(id)}><b>{n}</b><span>{d}</span></button>)}</div><div className="setup-actions"><button onClick={()=>p.setStep("channel")}>GERİ</button><button className="primary-seal" disabled={!p.name.trim()||!p.ruler.trim()} onClick={()=>p.setStep("general")}>PARSELİ TAHSİS ET</button></div></section>}
 {p.step==="general"&&<section className="setup-card"><div className="step-count">III / III</div><p className="eyebrow">GENERALİNİ UYANDIR</p><h2>BYOK modelini bağla</h2><p>Anahtarınız sunucu üzerinden yalnızca seçtiğiniz sağlayıcıya yapılan istek sırasında kullanılır; oyun kaydına veya tarayıcı deposuna yazılmaz.</p><div className="form-grid"><label>Sağlayıcı<select value={p.provider} onChange={e=>{const next=e.target.value as keyof typeof modelOptions;p.setProvider(next);p.setModel(modelOptions[next][0].id)}}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label><label>Model<select value={p.model} onChange={e=>p.setModel(e.target.value)}>{modelOptions[p.provider].map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label><label className="wide">API anahtarı<input type="password" value={p.apiKey} onChange={e=>p.setApiKey(e.target.value)} placeholder="Bağlanırken gerçek sağlayıcı isteğiyle doğrulanır" autoComplete="off"/></label></div>{p.error&&<div className="connection-error">{p.error}</div>}<div className="key-warning">Sayfa yenilenirse anahtar güvenlik nedeniyle unutulur ve General&apos;i yeniden bağlamanız gerekir. Üretim ve dünya zamanı bundan etkilenmez.</div><div className="setup-actions"><button onClick={()=>p.setStep("kingdom")}>GERİ</button><button onClick={()=>p.found(false)}>GENERAL SESSİZKEN BAŞLA</button><button className="primary-seal" disabled={p.connecting||!p.apiKey.trim()} onClick={p.connect}>{p.connecting?"DOĞRULANIYOR…":"GENERALİ BAĞLA VE TAHTA ÇIK"}</button></div></section>}
 </main>}
