"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import KingdomScene from "./KingdomScene";
import ChannelWorldMap from "./ChannelWorldMap";
import RichMessage from "./RichMessage";
import AccountGate, { type Account } from "./AccountGate";

type Key="gold"|"food"|"stone"|"wood"|"iron"|"ale"; type Res=Record<Key,number>;
type Building={type:string;name:string;category:string;level:number}; type Queue={kind:"building"|"unit";type:string;name:string;targetLevel?:number;count?:number;startedAt?:number;completesAt:number};
type Notice={kind:string;text:string;at:number}; type Tab="meclis"|"binalar"|"ordu"|"defter"|"diyar"; type Setup="welcome"|"channel"|"kingdom"|"general";
type GeneralAction={name:string;arguments:Record<string,unknown>};
type Channel={id:string;name:string;detail:string;speed:number;remaining:string;players?:number;maxPlayers?:number;durationDays?:number};
type IntelReport={id:string;name:string;ruler:string;terrain:string;keepLevel:number;population:number;buildingCount:number;army:number;resources:Record<string,number>};
type WorldKingdom={id:string;name:string|null;terrain:string;position:{x:number;z:number};discovered:boolean;mission:{status:"pending"|"succeeded"|"failed"|"detected";completesAt:number;successChance:number}|null;report:IntelReport|null};
type SharedMine={mine:{id:string;name:string;oreRemaining:number;extractedOre:number;totalWorkers:number;position:{x:number;z:number}};participants:Array<{id:string;name:string;workers:number;self:boolean}>};
type TerrainId="plain"|"forest"|"mountain"|"riverbank";
type Game={version:2;kingdomName:string;rulerName:string;channel:string;channelId?:string;speed:number;terrain:TerrainId;foundedAt:number;lastTickAt:number;protectionEndsAt:number;resources:Res;population:number;capacity:number;popularity:number;reputation:number;loyalty:number;taxRate:number;quota:number;quotaAt:number;buildings:Building[];units:Record<string,number>;queue:Queue|null;notices:Notice[];provider:string|null;model:string|null;generalConnected:boolean;strategyNote?:string;startingReserveGranted?:boolean};
// Yerel yedek hesap kimliğine göre ayrılır. Ortak bir anahtar kullanıldığında aynı
// tarayıcıda açılan yeni hesap, önceki hesabın krallığını devralıp buluta yazıyordu.
const LEGACY_STORE="demirkale.game.v2";
const storeKey=(accountId:string)=>`${LEGACY_STORE}:${accountId}`;
const modelOptions={
 openai:[{id:"gpt-5.6-terra",label:"GPT-5.6 Terra — Dengeli (önerilen)"},{id:"gpt-5.6-sol",label:"GPT-5.6 Sol — En güçlü"},{id:"gpt-5.6-luna",label:"GPT-5.6 Luna — Hızlı ve ekonomik"},{id:"gpt-5.5",label:"GPT-5.5 — Güçlü"},{id:"gpt-5.4-mini",label:"GPT-5.4 mini — Ekonomik"}],
 anthropic:[{id:"claude-sonnet-5",label:"Claude Sonnet 5 — Dengeli (önerilen)"},{id:"claude-opus-5",label:"Claude Opus 5 — En güçlü"},{id:"claude-fable-5",label:"Claude Fable 5 — Uzun görevler"},{id:"claude-haiku-4-5",label:"Claude Haiku 4.5 — Hızlı ve ekonomik"}]
} as const;
const fallbackChannels:Channel[]=[{id:"standard",name:"Standart Sezon III",detail:"84 gün · ×1 tempo · 0/300 Kral",speed:1,remaining:"84 gün"},{id:"frontier",name:"Sınır Boyu",detail:"28 gün · ×4 tempo · 0/120 Kral",speed:4,remaining:"28 gün"},{id:"rapid",name:"Hızlı Taç",detail:"7 gün · ×24 tempo · 0/80 Kral",speed:24,remaining:"7 gün"}];
const terrainCatalog:Record<TerrainId,{label:string;description:string;bonus:string;food:number;wood:number;stone:number;iron:number;defense:number;travel:number}>={
 plain:{label:"OVA",description:"Açık tarla ve otlaklar",bonus:"Dengeli üretim · normal hareket",food:1,wood:1,stone:1,iron:1,defense:1,travel:1},
 forest:{label:"ORMAN",description:"Sık ağaçlık ve dar patikalar",bonus:"+%25 odun · +%16 savunma · yavaş hareket",food:.85,wood:1.25,stone:1,iron:1,defense:1.16,travel:.85},
 mountain:{label:"DAĞ",description:"Kayalık sırtlar ve maden damarları",bonus:"+%30 taş/demir · +%25 savunma · çok yavaş hareket",food:.75,wood:.9,stone:1.3,iron:1.3,defense:1.25,travel:.65},
 riverbank:{label:"NEHİR KIYISI",description:"Verimli kıyı ve geniş geçit",bonus:"+%25 yiyecek · +%8 savunma · yavaş geçiş",food:1.25,wood:1,stone:.9,iron:.9,defense:1.08,travel:.75},
};
const catalog=[
 {type:"wheat_farm",name:"Buğday Tarlası",category:"Ekonomi",unlock:1,seconds:3600,cost:{wood:80},detail:"+18 yiyecek/sa"},{type:"lumberjack",name:"Oduncu Kulübesi",category:"Ekonomi",unlock:1,seconds:3600,cost:{gold:40,stone:25},detail:"+22 odun/sa"},{type:"quarry",name:"Taş Ocağı",category:"Ekonomi",unlock:1,seconds:5400,cost:{wood:100,gold:60},detail:"+16 taş/sa"},{type:"town_square",name:"Meydan",category:"Yönetim",unlock:1,seconds:7200,cost:{wood:120,stone:80},detail:"+80 nüfus kapasitesi"},{type:"barracks",name:"Kışla",category:"Askerî",unlock:1,seconds:9000,cost:{wood:170,stone:140},detail:"Temel birlikleri açar"},{type:"apple_orchard",name:"Elma Bahçesi",category:"Ekonomi",unlock:1,seconds:4200,cost:{wood:90,gold:30},detail:"+10 yiyecek/sa"},{type:"mill",name:"Değirmen",category:"Ekonomi",unlock:2,seconds:10800,cost:{wood:100,stone:120},detail:"Buğday zincirini büyütür"},{type:"market",name:"Pazar",category:"Ekonomi",unlock:2,seconds:14400,cost:{wood:160,stone:80},detail:"3 açık teklif yuvası"},{type:"wall",name:"Sur",category:"Askerî",unlock:3,seconds:28800,cost:{stone:500,wood:100},detail:"+%20 savunma"},{type:"mine",name:"Maden",category:"Ekonomi",unlock:1,seconds:10800,cost:{wood:150,stone:80},detail:"50.000 cevher rezervi"}
] as const;
const meta:Array<[Key,string]>=[["gold","ALTIN"],["food","YİYECEK"],["stone","TAŞ"],["wood","ODUN"],["iron","DEMİR"],["ale","BİRA"]];
const fmt=(n:number)=>new Intl.NumberFormat("tr-TR").format(Math.max(0,Math.round(n))); const keep=(g:Game)=>g.buildings.find(b=>b.type==="keep")?.level??1; const qph=(l:number)=>l>=5?6:l>=3?5:4;
const keepSeconds=[0,10800,28800,64800,172800,388800];
const affordable=(r:Res,c:Partial<Res>)=>Object.entries(c).every(([k,v])=>r[k as Key]>=(v??0)); const costFor=(base:Partial<Res>,level:number)=>Object.fromEntries(Object.entries(base).map(([k,v])=>[k,Math.ceil((v??0)*Math.pow(1.65,level))])) as Partial<Res>;
const left=(at:number,now:number)=>{const s=Math.max(0,Math.ceil((at-now)/1000));return s>=3600?`${Math.floor(s/3600)}sa ${Math.floor(s%3600/60)}dk`:s>=60?`${Math.floor(s/60)}dk ${s%60}sn`:`${s}sn`};
function rates(g:Game):Res{const l=Object.fromEntries(g.buildings.map(b=>[b.type,b.level])),terrain=terrainCatalog[g.terrain]??terrainCatalog.plain;return{gold:g.population*g.taxRate/100*.22,food:((l.wheat_farm??0)*18+(l.apple_orchard??0)*10)*terrain.food-g.population*.035,stone:(l.quarry??0)*16*terrain.stone,wood:(l.lumberjack??0)*22*terrain.wood,iron:(l.mine??0)*7*terrain.iron,ale:0}}
function tick(g:Game,now:number):Game{const h=Math.min(24,(now-g.lastTickAt)/3_600_000*g.speed);if(h<=0)return g;const rt=rates(g),resources={...g.resources};meta.forEach(([k])=>resources[k]=Math.max(0,resources[k]+rt[k]*h));let buildings=g.buildings,units=g.units,queue=g.queue,notices=g.notices;if(queue&&queue.completesAt<=now){if(queue.kind==="building"){const old=buildings.find(b=>b.type===queue!.type),item=catalog.find(b=>b.type===queue!.type);buildings=old?buildings.map(b=>b.type===queue!.type?{...b,level:queue!.targetLevel!}:b):[...buildings,{type:queue.type,name:queue.name.replace(/ Sv\.\d+$/,"")||item?.name||queue.name,category:item?.category??"Yönetim",level:queue.targetLevel??1}]}else units={...units,[queue.type]:(units[queue.type]??0)+(queue.count??0)};notices=[{kind:"TAMAMLANDI",text:`${queue.name} tamamlandı.`,at:now},...notices].slice(0,20);queue=null}const lv=keep({...g,buildings}),sq=buildings.find(b=>b.type==="town_square")?.level??0,capacity=150+sq*80+(lv-1)*50;const popularity=Math.max(0,Math.min(100,g.popularity+((15-g.taxRate)*.025+(rt.food>=0?.06:-.18))*h));const growth=popularity>=50&&rt.food>=0?( .08+sq*.04)*h:popularity<20?-.2*h:0;const qHours=Math.floor((now-g.quotaAt)/3_600_000);return{...g,resources,popularity,population:Math.max(20,Math.min(capacity,g.population+growth)),capacity,buildings,units,queue,notices,quota:Math.min(qph(lv)*2,g.quota+qHours*qph(lv)),quotaAt:qHours?g.quotaAt+qHours*3_600_000:g.quotaAt,lastTickAt:now}}

export default function KingdomGame(){
 const[ready,setReady]=useState(false),[account,setAccount]=useState<Account|null|undefined>(undefined),[setup,setSetup]=useState<Setup>("welcome"),[availableChannels,setAvailableChannels]=useState<Channel[]>(fallbackChannels),[selected,setSelected]=useState<Channel>(fallbackChannels[2]);const[name,setName]=useState(""),[ruler,setRuler]=useState(""),[terrain,setTerrain]=useState<TerrainId>("plain"),[provider,setProvider]=useState<keyof typeof modelOptions>("openai"),[model,setModel]=useState("gpt-5.6-terra"),[apiKey,setApiKey]=useState("");
 const[game,setGame]=useState<Game|null>(null),[now,setNow]=useState(Date.now()),[tab,setTab]=useState<Tab>("meclis"),[night,setNight]=useState(false),[worldView,setWorldView]=useState(false),[message,setMessage]=useState(""),[chat,setChat]=useState<Array<{who:string;text:string}>>([]),[toast,setToast]=useState(""),[connecting,setConnecting]=useState(false),[generalError,setGeneralError]=useState(""),[showConnect,setShowConnect]=useState(false),[tutorialStep,setTutorialStep]=useState<number|null>(null),[cloudReady,setCloudReady]=useState(false),[cloudStatus,setCloudStatus]=useState("BULUT ARANIYOR"),[cloudUser,setCloudUser]=useState(""),[storedByok,setStoredByok]=useState(false),[replaceByok,setReplaceByok]=useState(false),[otherKingdoms,setOtherKingdoms]=useState<WorldKingdom[]>([]),[worldDefense,setWorldDefense]=useState<{active:boolean;activeUntil:number|null}>({active:false,activeUntil:null}),[incomingAlerts,setIncomingAlerts]=useState(0),[sharedMine,setSharedMine]=useState<SharedMine|null>(null),[worldBusy,setWorldBusy]=useState(false);
 const lastCloudSave=useRef(0),saving=useRef(false),worldRefresh=useRef<(()=>void)|null>(null);
 useEffect(()=>{let local:Game|null=null;localStorage.removeItem(LEGACY_STORE);void(async()=>{try{const authResponse=await fetch("/api/auth",{cache:"no-store"});const authData=await authResponse.json() as {user?:Account|null};if(!authResponse.ok||!authData.user){setAccount(null);setReady(true);return}setAccount(authData.user);setCloudUser(authData.user.displayName);const savedLocal=localStorage.getItem(storeKey(authData.user.id));if(savedLocal)try{local=JSON.parse(savedLocal) as Game}catch{localStorage.removeItem(storeKey(authData.user.id))}const [saveResponse,channelResponse,byokResponse]=await Promise.all([fetch("/api/save",{cache:"no-store"}),fetch("/api/channels",{cache:"no-store"}),fetch("/api/byok",{cache:"no-store"})]);const data=await saveResponse.json() as {game?:Game|null};if(!saveResponse.ok)throw new Error("Bulut kaydı açılamadı");const byokData=await byokResponse.json() as {connected?:boolean;provider?:keyof typeof modelOptions;model?:string};if(byokResponse.ok&&byokData.connected&&byokData.provider&&byokData.model){setStoredByok(true);setProvider(byokData.provider);setModel(byokData.model)}const channelData=await channelResponse.json() as {channels?:Array<{id:string;name:string;speed:number;durationDays:number;maxPlayers:number;players:number;endsAt?:string|null}>};if(channelResponse.ok&&channelData.channels?.length){const mapped=channelData.channels.map(channel=>{const days=channel.endsAt?Math.max(0,Math.ceil((new Date(channel.endsAt).getTime()-Date.now())/86_400_000)):channel.durationDays;return{id:channel.id,name:channel.name,speed:channel.speed,durationDays:channel.durationDays,maxPlayers:channel.maxPlayers,players:Number(channel.players),detail:`${channel.durationDays} gün · ×${channel.speed} tempo · ${Number(channel.players)}/${channel.maxPlayers} Kral`,remaining:`${days} gün`}});setAvailableChannels(mapped);setSelected(mapped[0])}const source=data.game||local;if(source)setGame({...tick(source,Date.now()),provider:byokData.connected?byokData.provider??source.provider:source.provider,model:byokData.connected?byokData.model??source.model:source.model,generalConnected:Boolean(byokData.connected)});setCloudStatus(data.game?"BULUTTAN YÜKLENDİ":"BULUT HAZIR")}catch{if(local)setGame({...tick(local,Date.now()),generalConnected:false});setCloudStatus("YEREL YEDEK")}finally{setCloudReady(true);setReady(true)}})();},[]);
 useEffect(()=>{const id=setInterval(()=>{const n=Date.now();setNow(n);setGame(g=>g?tick(g,n):null)},1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!game){setOtherKingdoms([]);setSharedMine(null);return}const channelId=game.channelId??availableChannels.find(channel=>channel.name===game.channel)?.id;if(!channelId)return;if(!game.channelId)setGame(current=>current?{...current,channelId}:current);let active=true;const loadWorld=async()=>{try{const [worldResponse,mineResponse]=await Promise.all([fetch(`/api/world?channelId=${encodeURIComponent(channelId)}`,{cache:"no-store"}),fetch(`/api/mine?channelId=${encodeURIComponent(channelId)}`,{cache:"no-store"})]);const worldData=await worldResponse.json() as {kingdoms?:WorldKingdom[];defense?:{active:boolean;activeUntil:number|null};incomingAlerts?:number};const mineData=await mineResponse.json() as SharedMine;if(active&&worldResponse.ok){setOtherKingdoms(worldData.kingdoms??[]);setWorldDefense(worldData.defense??{active:false,activeUntil:null});setIncomingAlerts(worldData.incomingAlerts??0)}if(active&&mineResponse.ok)setSharedMine(mineData)}catch{if(active)setOtherKingdoms([])}};worldRefresh.current=()=>void loadWorld();void loadWorld();const timer=setInterval(()=>void loadWorld(),10_000);return()=>{active=false;worldRefresh.current=null;clearInterval(timer)}},[game?.channelId,game?.channel,availableChannels]);
 useEffect(()=>{if(game&&!game.startingReserveGranted)setGame({...game,quota:Math.max(6,game.quota),startingReserveGranted:true,notices:[{kind:"DİVAN",text:"Başlangıç yönetim rezervi tanımlandı: 6 emir hazır, 8 emre kadar birikebilir.",at:Date.now()},...game.notices]})},[game]);
 useEffect(()=>{if(game&&ready&&account)localStorage.setItem(storeKey(account.id),JSON.stringify(game));if(!game||!cloudReady||saving.current||Date.now()-lastCloudSave.current<5000)return;saving.current=true;lastCloudSave.current=Date.now();setCloudStatus("KAYDEDİLİYOR");void fetch("/api/save",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({game})}).then(response=>{if(!response.ok)throw new Error();setCloudStatus("BULUTA KAYDEDİLDİ")}).catch(()=>setCloudStatus("YEREL YEDEK")).finally(()=>{saving.current=false})},[game,ready,cloudReady,account]);
 const lv=game?keep(game):1,rt=useMemo(()=>game?rates(game):null,[game]);
 function found(connected:boolean,introduction?:string){const t=Date.now(),terrainInfo=terrainCatalog[terrain];const g:Game={version:2,kingdomName:name.trim(),rulerName:ruler.trim(),channel:selected.name,channelId:selected.id,speed:selected.speed,terrain,foundedAt:t,lastTickAt:t,protectionEndsAt:t+4*86_400_000,resources:{gold:1000,food:500,stone:300,wood:300,iron:100,ale:0},population:100,capacity:150,popularity:50,reputation:50,loyalty:75,taxRate:15,quota:2,quotaAt:t,buildings:[{type:"keep",name:"Kale",category:"Yönetim",level:1},{type:"wheat_farm",name:"Buğday Tarlası",category:"Ekonomi",level:1},{type:"lumberjack",name:"Oduncu Kulübesi",category:"Ekonomi",level:1}],units:{spearman:0},queue:null,notices:[{kind:"ARAZİ",text:`${terrainInfo.label} parseli tahsis edildi: ${terrainInfo.bonus}.`,at:t},{kind:"KURULUŞ",text:"Krallığınız dış çeperdeki boş parsele kuruldu. Dört günlük korumanız başladı.",at:t}],provider:connected?provider:null,model:connected?model:null,generalConnected:connected,strategyNote:"Ekonomiyi dengede tut, halkı aç bırakma ve koruma bitene kadar savunmayı hazırla."};void fetch("/api/channels",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({channelId:selected.id})}).then(async response=>{if(!response.ok){const data=await response.json() as {error?:string};setToast(data.error||"Channel katılımı kaydedilemedi.")}});setGame(g);setChat([{who:connected?"General Aldric":"Saray Kâtibi",text:connected?(introduction||"Bağlantı doğrulandı. İlk hedefinizi ve yönetim doktrinimizi belirleyin."):"General henüz sessiz. Üretim ve kuyruklar çalışır; yeni yönetim kararları için BYOK General'i bağlamalısınız."}]);if(!localStorage.getItem("demirkale.tutorial.done"))setTutorialStep(0)}
 function kingdomContext(g:Game|null){if(!g)return{name:name.trim(),ruler:ruler.trim(),terrain:terrainCatalog[terrain],keepLevel:1,population:100,popularity:50,loyalty:75,quota:2,strategyNote:"Henüz belirlenmedi",resources:{gold:1000,food:500,stone:300,wood:300,iron:100,ale:0},hourlyRates:{gold:3.3,food:14.5,stone:0,wood:22,iron:0,ale:0},buildings:[{name:"Kale",level:1},{name:"Buğday Tarlası",level:1},{name:"Oduncu Kulübesi",level:1}],units:{spearman:0},channelSpeed:selected.speed,activeConstruction:null};const level=keep(g),buildTimes:Array<{name:string;nextLevel:number;seconds:number;cost:Partial<Res>}>=catalog.filter(item=>item.unlock<=level).map(item=>{const current=g.buildings.find(b=>b.type===item.type)?.level??0;return{name:item.name,nextLevel:current+1,seconds:Math.round(item.seconds/g.speed),cost:costFor(item.cost,current)}});if(level<6){const keepUpgradeCosts:Array<Partial<Res>>=[{},{gold:300,stone:400,wood:250},{gold:700,stone:900,wood:600},{gold:1500,stone:1800,wood:1100},{gold:3500,stone:4000,wood:2500,iron:300},{gold:8000,stone:9000,wood:5000,iron:800}];buildTimes.unshift({name:"Kale",nextLevel:level+1,seconds:Math.round(keepSeconds[level]/g.speed),cost:keepUpgradeCosts[level]})}return{name:g.kingdomName,ruler:g.rulerName,terrain:terrainCatalog[g.terrain]??terrainCatalog.plain,keepLevel:level,population:g.population,popularity:g.popularity,loyalty:g.loyalty,quota:g.quota,strategyNote:g.strategyNote??"Ekonomiyi dengede tut ve halkı aç bırakma.",resources:g.resources,hourlyRates:rates(g),buildings:g.buildings.map(b=>({name:b.name,level:b.level})),units:g.units,channelSpeed:g.speed,activeConstruction:g.queue?{name:g.queue.name,secondsRemaining:Math.max(0,Math.ceil((g.queue.completesAt-Date.now())/1000))}:null,buildTimes,
   // Maden, komşular ve nöbet durumu olmadan General bu alanlarda körlemesine karar verir.
   mine:sharedMine?{workers:sharedMine.participants.find(p=>p.self)?.workers??0,totalWorkers:sharedMine.mine.totalWorkers,oreRemaining:sharedMine.mine.oreRemaining}:null,
   neighbors:otherKingdoms.map((kingdom,index)=>({ordinal:index+1,name:kingdom.discovered&&kingdom.name?kingdom.name:"Bilinmeyen Sancak",discovered:kingdom.discovered,scouting:kingdom.mission?.status==="pending"})),
   counterIntelligence:{active:worldDefense.active,minutesRemaining:worldDefense.activeUntil?Math.max(0,Math.ceil((worldDefense.activeUntil-Date.now())/60_000)):0}}}
 function closeTutorial(){localStorage.setItem("demirkale.tutorial.done","1");setTutorialStep(null)}
 function advanceTutorial(){if(tutorialStep===null)return;const next=tutorialStep+1;if(next>=5)return closeTutorial();setTutorialStep(next);if(next===1)setTab("meclis");if(next===2)setTab("binalar");if(next===3)setTab("defter");if(next===4)setTab("diyar")}
 async function worldAction(action:"scout"|"defend",targetId?:string){if(!game?.channelId||worldBusy)return;setWorldBusy(true);try{const response=await fetch("/api/world",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,channelId:game.channelId,targetId})});const data=await response.json() as {error?:string;completesAt?:number;successChance?:number;activeUntil?:number};if(!response.ok)throw new Error(data.error||"Dünya emri uygulanamadı.");if(action==="defend")setWorldDefense({active:true,activeUntil:data.activeUntil??null});else setOtherKingdoms(items=>items.map(item=>item.id===targetId?{...item,mission:{status:"pending",completesAt:data.completesAt??Date.now(),successChance:data.successChance??10}}:item));setToast(action==="defend"?"Karşı-istihbarat nöbeti bir saatliğine kuruldu.":`Ajan yola çıktı · başarı ihtimali %${data.successChance??10}.`)}catch(error){setToast(error instanceof Error?error.message:"Dünya emri uygulanamadı.")}finally{setWorldBusy(false)}}
 async function mineAction(action:"join"|"leave"){if(!game?.channelId||worldBusy)return;setWorldBusy(true);try{const response=await fetch("/api/mine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,channelId:game.channelId,workers:5})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Maden emri uygulanamadı.");setToast(action==="join"?"Ortak madene 5 işçi gönderildi.":"İşçiler ortak madenden çekildi.");const mineResponse=await fetch(`/api/mine?channelId=${encodeURIComponent(game.channelId)}`,{cache:"no-store"});if(mineResponse.ok)setSharedMine(await mineResponse.json() as SharedMine)}catch(error){setToast(error instanceof Error?error.message:"Maden emri uygulanamadı.")}finally{setWorldBusy(false)}}
 async function askGeneral(mode:"test"|"chat",text?:string){const history=chat.slice(-8).map(item=>({role:item.who===(game?.rulerName||ruler.trim())?"king":"general",text:item.text}));const response=await fetch("/api/general",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,model,...(apiKey?{apiKey}:{}),mode,message:text,history,kingdom:kingdomContext(game)})});const data=await response.json() as {text?:string;actions?:GeneralAction[];error?:string};if(!response.ok)throw new Error(data.error||"General bağlantısı başarısız oldu.");return{text:data.text||"General bağlantısı doğrulandı.",actions:data.actions??[]}}
 async function persistByok(){const response=await fetch("/api/byok",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({provider,model,apiKey})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"BYOK bağlantısı kaydedilemedi.");setStoredByok(true);setReplaceByok(false);setApiKey("")}
 async function connectAndFound(){if(!apiKey.trim())return setGeneralError("API anahtarını girmelisiniz.");setConnecting(true);setGeneralError("");try{const intro=await askGeneral("test");await persistByok();found(true,intro.text)}catch(error){setGeneralError(error instanceof Error?error.message:"Bağlantı kurulamadı.")}finally{setConnecting(false)}}
 async function reconnectGeneral(){if(!game||(!apiKey.trim()&&!storedByok))return setGeneralError("API anahtarını girmelisiniz.");setConnecting(true);setGeneralError("");try{const intro=await askGeneral("test");if(apiKey.trim())await persistByok();setGame({...game,provider,model,generalConnected:true});setChat(x=>[...x,{who:"General Aldric",text:intro.text}]);setShowConnect(false);setToast("General bağlantısı hesaba şifreli olarak kaydedildi.")}catch(error){setGeneralError(error instanceof Error?error.message:"Bağlantı kurulamadı.")}finally{setConnecting(false)}}
 function debit(g:Game,c:Partial<Res>){const r={...g.resources};Object.entries(c).forEach(([k,v])=>r[k as Key]-=v??0);return r}
 function build(type:string){if(!game||game.queue)return setToast("Aynı anda yalnızca bir kuyruk çalışabilir.");if(game.quota<1)return setToast("Emir kotanız tükendi.");const item=catalog.find(b=>b.type===type);if(!item)return;const old=game.buildings.find(b=>b.type===type),current=old?.level??0;if(item.unlock>lv)return setToast(`Kale Sv.${item.unlock} gerekli.`);const cost=costFor(item.cost,current);if(!affordable(game.resources,cost))return setToast("Bu yapı için kaynak yetersiz.");setGame({...game,resources:debit(game,cost),quota:game.quota-1,queue:{kind:"building",type,name:`${item.name} Sv.${current+1}`,targetLevel:current+1,startedAt:now,completesAt:now+item.seconds/game.speed*1000},notices:[{kind:"EMİR",text:`${item.name} için inşa emri verildi.`,at:now},...game.notices]});setToast("Emir mühürlendi; inşaat başladı.")}
 function upgradeKeep(){if(!game||game.queue||game.quota<1||lv>=6)return setToast(game?.queue?"Önce mevcut kuyruk tamamlanmalı.":"Bu emir şu anda verilemiyor.");const costs:Array<Partial<Res>>=[{},{gold:300,stone:400,wood:250},{gold:700,stone:900,wood:600},{gold:1500,stone:1800,wood:1100},{gold:3500,stone:4000,wood:2500,iron:300},{gold:8000,stone:9000,wood:5000,iron:800}],cost=costs[lv];if(!affordable(game.resources,cost))return setToast("Kale yükseltmesi için kaynak yetersiz.");const seconds=keepSeconds[lv];setGame({...game,resources:debit(game,cost),quota:game.quota-1,queue:{kind:"building",type:"keep",name:`Kale Sv.${lv+1}`,targetLevel:lv+1,startedAt:now,completesAt:now+seconds/game.speed*1000}})}
 function train(){if(!game||game.queue||game.quota<1)return setToast("Kuyruk veya emir kotası uygun değil.");if(!game.buildings.some(b=>b.type==="barracks"))return setToast("Önce Kışla kurmalısınız.");const c={gold:80,food:100,iron:10};if(!affordable(game.resources,c))return setToast("10 Mızrakçı için kaynak yetersiz.");setGame({...game,resources:debit(game,c),quota:game.quota-1,population:Math.max(20,game.population-10),queue:{kind:"unit",type:"spearman",name:"10 Mızrakçı",count:10,startedAt:now,completesAt:now+12000/game.speed*1000}})}
 function festival(){if(!game||game.quota<1)return setToast("Emir kotası yetersiz.");const c={gold:120,food:150};if(!affordable(game.resources,c))return setToast("Şenlik için kaynak yetersiz.");setGame({...game,resources:debit(game,c),quota:game.quota-1,popularity:Math.min(100,game.popularity+12),notices:[{kind:"ŞENLİK",text:"Halk meydanda toplandı; rıza 12 puan yükseldi.",at:now},...game.notices]})}
 function executeGeneralActions(base:Game,actions:GeneralAction[]){let next=tick(base,Date.now());const actionNow=Date.now();const results:string[]=[],remote:GeneralAction[]=[];const success=(text:string)=>{results.push(`✓ ${text}`);next={...next,loyalty:Math.min(100,next.loyalty+.5)}};const blocked=(text:string)=>results.push(`✕ ${text}`);const majorSpend=(cost:Partial<Res>)=>Object.entries(cost).some(([key,value])=>(value??0)>Math.max(1,next.resources[key as Key])*.65);
  for(const action of actions.slice(0,3)){
   if(action.name==="build_structure"){
    if(next.queue){blocked(`İnşa emri uygulanmadı: ${next.queue.name} kuyruğu dolu.`);continue}if(next.quota<1){blocked("İnşa emri uygulanmadı: emir kotası tükendi.");continue}
    const type=String(action.arguments.building_type??""),target=Math.floor(Number(action.arguments.target_level)),confirmed=action.arguments.confirmed_risk===true;const level=keep(next);
    if(type==="keep"){
     if(target!==level+1||level>=6){blocked(`Kale yalnızca Sv.${level+1} seviyesine yükseltilebilir.`);continue}const costs:Array<Partial<Res>>=[{},{gold:300,stone:400,wood:250},{gold:700,stone:900,wood:600},{gold:1500,stone:1800,wood:1100},{gold:3500,stone:4000,wood:2500,iron:300},{gold:8000,stone:9000,wood:5000,iron:800}],cost=costs[level];if(!affordable(next.resources,cost)){blocked("Kale yükseltmesi kaynak yetersizliği nedeniyle engellendi.");continue}if(majorSpend(cost)&&!confirmed){blocked("Kale yükseltmesi hazinenin kritik bölümünü tüketeceği için açık teyit bekliyor.");continue}next={...next,resources:debit(next,cost),quota:next.quota-1,queue:{kind:"building",type:"keep",name:`Kale Sv.${target}`,targetLevel:target,startedAt:actionNow,completesAt:actionNow+keepSeconds[level]/next.speed*1000}};success(`Kale Sv.${target} yükseltmesi başlatıldı.`);continue
    }
    const item=catalog.find(entry=>entry.type===type);if(!item){blocked("Bilinmeyen bina emri reddedildi.");continue}const old=next.buildings.find(b=>b.type===type),current=old?.level??0;if(target!==current+1){blocked(`${item.name} yalnızca Sv.${current+1} seviyesine çıkarılabilir.`);continue}if(item.unlock>level){blocked(`${item.name} için Kale Sv.${item.unlock} gerekli.`);continue}const cost=costFor(item.cost,current);if(!affordable(next.resources,cost)){blocked(`${item.name} için kaynak yetersiz; General emri beklemeye aldı.`);continue}if(type!=="wheat_farm"&&type!=="apple_orchard"&&(rates(next).food<0||next.resources.food<100)&&!confirmed){blocked(`${item.name} emri yiyecek krizi çözülene kadar ertelendi.`);continue}if(majorSpend(cost)&&!confirmed){blocked(`${item.name} hazinenin kritik bölümünü tüketeceği için açık teyit bekliyor.`);continue}next={...next,resources:debit(next,cost),quota:next.quota-1,queue:{kind:"building",type,name:`${item.name} Sv.${target}`,targetLevel:target,startedAt:actionNow,completesAt:actionNow+item.seconds/next.speed*1000},notices:[{kind:"GENERAL",text:`${item.name} Sv.${target} emri uygulandı.`,at:actionNow},...next.notices]};success(`${item.name} Sv.${target} inşaatı başlatıldı.`);continue
   }
   if(action.name==="accelerate_construction"){
    if(!next.queue?.startedAt){blocked("Hızlandırılacak aktif kuyruk yok.");continue}const active=next.queue,seconds=Math.max(0,Math.ceil((active.completesAt-actionNow)/1000)),cost=Math.max(10,Math.ceil(seconds/60)*2);if(next.resources.gold<cost){blocked(`Hızlandırma engellendi: ${cost} altın gerekiyor, hazinede ${Math.floor(next.resources.gold)} var.`);continue}let completedBuildings=next.buildings,completedUnits=next.units;if(active.kind==="building"){const old=next.buildings.find(building=>building.type===active.type),item=catalog.find(building=>building.type===active.type);completedBuildings=old?next.buildings.map(building=>building.type===active.type?{...building,level:active.targetLevel??building.level}:building):[...next.buildings,{type:active.type,name:active.name.replace(/ Sv\.\d+$/,"")||item?.name||active.name,category:item?.category??"Yönetim",level:active.targetLevel??1}]}else completedUnits={...next.units,[active.type]:(next.units[active.type]??0)+(active.count??0)};next={...next,resources:{...next.resources,gold:next.resources.gold-cost},buildings:completedBuildings,units:completedUnits,queue:null,notices:[{kind:"TAMAMLANDI",text:`${active.name} hızlandırılarak tamamlandı.`,at:actionNow},...next.notices].slice(0,20)};success(`${active.name} ${cost} altın harcanarak tamamlandı.`);continue
   }
   if(action.name==="train_unit"){
    if(next.queue){blocked(`Eğitim emri uygulanmadı: ${next.queue.name} kuyruğu dolu.`);continue}if(next.quota<1){blocked("Eğitim emri uygulanmadı: emir kotası tükendi.");continue}if(!next.buildings.some(b=>b.type==="barracks")){blocked("Eğitim engellendi: önce Kışla kurulmalı.");continue}const unit=String(action.arguments.unit_type??""),count=Math.floor(Number(action.arguments.count)),confirmed=action.arguments.confirmed_risk===true;if(unit!=="spearman"||count<1||count>50){blocked("Desteklenmeyen birlik veya adet emri reddedildi.");continue}const cost={gold:count*8,food:count*10,iron:count};if(!affordable(next.resources,cost)||next.population-count<20){blocked(`${count} Mızrakçı için kaynak ya da çalışan nüfus yetersiz.`);continue}if((rates(next).food<0||count>next.population*.25)&&!confirmed){blocked("Eğitim emri yiyecek/nüfus riski nedeniyle açık teyit bekliyor.");continue}next={...next,resources:debit(next,cost),quota:next.quota-1,population:next.population-count,queue:{kind:"unit",type:"spearman",name:`${count} Mızrakçı`,count,startedAt:actionNow,completesAt:actionNow+count*1200/next.speed*1000}};success(`${count} Mızrakçının eğitimi başlatıldı.`);continue
   }
   if(action.name==="host_festival"){
    const cost={gold:120,food:150};if(next.quota<1){blocked("Şenlik engellendi: emir kotası tükendi.");continue}if(!affordable(next.resources,cost)){blocked("Şenlik engellendi: 120 altın ve 150 yiyecek gerekli.");continue}next={...next,resources:debit(next,cost),quota:next.quota-1,popularity:Math.min(100,next.popularity+12),notices:[{kind:"GENERAL",text:"General halk için şenlik düzenledi.",at:actionNow},...next.notices]};success("Şenlik düzenlendi; halkın rızası 12 puan yükseldi.");continue
   }
   if(action.name==="set_tax_rate"){
    const rate=Math.floor(Number(action.arguments.rate_percent)),confirmed=action.arguments.confirmed_risk===true;if(!Number.isFinite(rate)||rate<0||rate>50){blocked("Geçersiz vergi oranı reddedildi.");continue}if(rate>30&&!confirmed){blocked(`%${rate} vergi halk için riskli; açık Kral teyidi olmadan uygulanmadı.`);continue}if(next.quota<1){blocked("Vergi emri uygulanmadı: emir kotası tükendi.");continue}next={...next,taxRate:rate,quota:next.quota-1,loyalty:Math.max(0,next.loyalty-(rate>30?2:0))};success(`Vergi oranı %${rate} olarak mühürlendi.`);continue
   }
   if(action.name==="set_strategy_note"){
    const note=String(action.arguments.note??"").trim();if(note.length<5||note.length>300){blocked("Yönetim doktrini geçersiz olduğu için kaydedilmedi.");continue}next={...next,strategyNote:note,notices:[{kind:"DOKTRİN",text:`Kralın yönetim doktrini güncellendi: ${note}`,at:actionNow},...next.notices]};success("Yönetim doktrini kaydedildi; sonraki kararlarımda bunu esas alacağım.");continue
   }
   // Maden, ajan ve nöbet emirleri sunucu uçlarına gider; burada sıraya alınır.
   if(action.name==="send_miners"||action.name==="recall_miners"||action.name==="send_scout"||action.name==="raise_counter_intelligence"){remote.push(action);continue}
   blocked(`Generalin önerdiği “${action.name}” aracı bu sürümde yetkili değil.`);
  }
  return{game:next,results,remote};
 }
 // Sunucu tarafı eylemler: sonuç metni her zaman API'nin gerçek cevabından üretilir.
 async function executeRemoteActions(actions:GeneralAction[],channelId:string|undefined){
  const results:string[]=[];
  if(!actions.length)return results;
  if(!channelId){actions.forEach(()=>results.push("✕ Bu emir için channel bilgisi çözülemedi."));return results}
  for(const action of actions){
   try{
    if(action.name==="send_miners"||action.name==="recall_miners"){
     const join=action.name==="send_miners",workers=Math.max(1,Math.min(20,Math.floor(Number(action.arguments.workers)||5)));
     const response=await fetch("/api/mine",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(join?{channelId,action:"join",workers}:{channelId,action:"leave"})});
     const data=await response.json() as {working?:boolean;workers?:number;error?:string};
     if(!response.ok){results.push(`✕ Maden emri uygulanmadı: ${data.error??"sunucu reddetti."}`);continue}
     results.push(join?`✓ Ortak madene ${data.workers??workers} işçi görevlendirildi.`:"✓ Madendeki işçiler geri çekildi.");
     continue;
    }
    if(action.name==="send_scout"){
     const ordinal=Math.floor(Number(action.arguments.target_ordinal));const target=otherKingdoms[ordinal-1];
     if(!target){results.push(`✕ Ajan emri uygulanmadı: ${ordinal}. sancak haritada yok.`);continue}
     const response=await fetch("/api/world",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"scout",channelId,targetId:target.id})});
     const data=await response.json() as {sent?:boolean;successChance?:number;error?:string};
     if(!response.ok){results.push(`✕ Ajan gönderilemedi: ${data.error??"sunucu reddetti."}`);continue}
     results.push(`✓ ${target.name??`${ordinal}. sancağa`} ajan yollandı; başarı ihtimali %${data.successChance??10}.`);
     continue;
    }
    const response=await fetch("/api/world",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"defend",channelId})});
    const data=await response.json() as {defended?:boolean;error?:string};
    results.push(response.ok?"✓ Karşı-istihbarat nöbeti bir saatliğine kuruldu.":`✕ Nöbet kurulamadı: ${data.error??"sunucu reddetti."}`);
   }catch{results.push("✕ Emir sunucuya iletilemedi.")}
  }
  return results;
 }
 async function submitOrder(order:string){if(!game||!order.trim()||connecting)return;setChat(x=>[...x,{who:game.rulerName,text:order.trim()}]);setMessage("");setTab("meclis");if(!game.generalConnected){setChat(x=>[...x,{who:"Saray Kâtibi",text:"General bağlantısı etkin değil. Hesabındaki BYOK bağlantısını yenilemelisin."}]);setShowConnect(true);return}setConnecting(true);try{const answer=await askGeneral("chat",order.trim()),execution=executeGeneralActions(game,answer.actions);if(answer.actions.length)setGame(execution.game);const remoteResults=await executeRemoteActions(execution.remote,game.channelId??availableChannels.find(channel=>channel.name===game.channel)?.id);const merged=[...execution.results,...remoteResults];const outcome=merged.length?`\n\n${merged.join("\n")}`:"";setChat(x=>[...x,{who:"General Aldric",text:`${answer.text}${outcome}`}]);if(remoteResults.some(line=>line.startsWith("✓")))worldRefresh.current?.()}catch(error){setChat(x=>[...x,{who:"Saray Kâtibi",text:error instanceof Error?error.message:"General yanıt veremedi."}]);setGame({...game,generalConnected:false});setShowConnect(true)}finally{setConnecting(false)}}
 async function send(e:React.FormEvent){e.preventDefault();await submitOrder(message)}
 function reset(){if(confirm("Krallığınız hem buluttan hem bu cihazdan silinsin ve yeniden başlansın mı?")){void fetch("/api/save",{method:"DELETE"});if(account)localStorage.removeItem(storeKey(account.id));setGame(null);setSetup("welcome");setCloudStatus("BULUT HAZIR")}}
 async function logout(){await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});if(account)localStorage.removeItem(storeKey(account.id));location.reload()}
 if(!ready)return <div className="boot-screen">DİYAR HAZIRLANIYOR…</div>;
 if(!account)return <AccountGate onAuthenticated={user=>{location.href=user.role==="admin"?"/admin":"/"}}/>;
 if(!game&&account.role==="admin")return <main className="account-gate"><div className="account-landscape"><i/><i/><i/></div><header><div className="brand-mark">♜</div><div className="title-block"><h1>DEMİRKALE</h1><p>YÖNETİCİ OTURUMU</p></div></header><section className="account-card admin-entry"><p className="eyebrow">YÖNETİM YETKİSİ DOĞRULANDI</p><h2>Yönetim Divanı hazır</h2><p>Channelları açıp kapatabilir, sezon ayarlarını belirleyebilir ve oyuncu hesaplarını yönetebilirsin.</p><a className="primary-seal" href="/admin">YÖNETİM DİVANINI AÇ</a><button onClick={logout}>YÖNETİCİ OTURUMUNU KAPAT</button></section></main>;
 if(!game)return <Onboarding channels={availableChannels} step={setup} setStep={setSetup} selected={selected} setSelected={setSelected} name={name} setName={setName} ruler={ruler} setRuler={setRuler} terrain={terrain} setTerrain={setTerrain} provider={provider} setProvider={setProvider} model={model} setModel={setModel} apiKey={apiKey} setApiKey={setApiKey} found={found} connect={connectAndFound} connecting={connecting} error={generalError}/>;
 return <main className={night?"app-shell night":"app-shell"}>{toast&&<button className="toast" onClick={()=>setToast("")}>{toast} ×</button>}{showConnect&&<div className="connect-overlay"><section className="connect-card"><button className="close-connect" onClick={()=>setShowConnect(false)}>×</button><p className="eyebrow">GENERALİ YENİDEN BAĞLA</p><h2>BYOK oturum bağlantısı</h2>{storedByok&&!replaceByok?<div className="stored-key"><b>✓ ANAHTAR HESABINDA KAYITLI</b><span>{provider} · {model}</span><button onClick={()=>setReplaceByok(true)}>ANAHTARI DEĞİŞTİR</button></div>:<div className="form-grid"><label>Sağlayıcı<select value={provider} onChange={e=>{const next=e.target.value as keyof typeof modelOptions;setProvider(next);setModel(modelOptions[next][0].id)}}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)}>{modelOptions[provider].map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label><label className="wide">API anahtarı<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off" placeholder="API anahtarını gir"/></label></div>}{generalError&&<div className="connection-error">{generalError}</div>}<p className="privacy-note">Anahtar hesabına AES-GCM ile şifreli kaydedilir; tarayıcıya geri gönderilmez ve yalnızca sağlayıcı isteği sırasında çözülür.</p><button className="primary-seal connect-submit" disabled={connecting||((!storedByok||replaceByok)&&!apiKey.trim())} onClick={reconnectGeneral}>{connecting?"DOĞRULANIYOR…":storedByok&&!replaceByok?"KAYITLI BAĞLANTIYLA DEVAM":"BAĞLANTIYI KAYDET"}</button></section></div>}<header className="topbar"><div className="brand-mark">♜</div><div className="title-block"><h1>{game.kingdomName.toLocaleUpperCase("tr")}</h1><p>KRALLIK SİMÜLASYONU</p></div><div className="channel-chip"><span>● AKTİF</span><b>{game.channel}</b><small>Gün 1 · Koruma {left(game.protectionEndsAt,now)}</small></div><div className="cloud-chip" title={cloudUser||"Hesaba bağlı kayıt"}>☁ {cloudStatus}</div>{account.role==="admin"&&<a className="admin-link" href="/admin">YÖNETİM</a>}<button className="day-toggle" onClick={()=>{setTutorialStep(0);setTab("meclis")}}>？ REHBER</button><button className="day-toggle" onClick={()=>setNight(x=>!x)}>{night?"☾ GECE":"☀ GÜNDÜZ"}</button><button className="profile-button" onClick={reset}>{game.rulerName} · Sıfırla</button><button className="profile-button" onClick={logout}>Çıkış</button></header>
 <section className="resource-ribbon">{meta.map(([k,label])=><div className="resource" key={k}><span>{label}</span><strong>{fmt(game.resources[k])}</strong><small className={(rt?.[k]??0)<0?"negative":""}>{(rt?.[k]??0)>=0?"+":""}{(rt?.[k]??0).toFixed(1)}/sa</small></div>)}<div className="population"><span>HALKIN RIZASI</span><strong>{Math.round(game.popularity)}</strong><div className="meter"><i style={{width:`${game.popularity}%`}}/></div><small>{Math.round(game.population)} / {game.capacity} nüfus</small></div></section>
 <section className="world-stage"><KingdomScene night={night} keepLevel={lv} developed={lv>=3&&game.buildings.length>=8} terrain={game.terrain} constructionName={game.queue?.kind==="building"?game.queue.name:undefined}/><div className="scene-title"><button className="world-view-toggle" onClick={()=>setWorldView(true)}>CHANNEL HARİTASINI AÇ</button><span>YENİ BAŞKENT · {(terrainCatalog[game.terrain]??terrainCatalog.plain).label}</span><h2>{game.kingdomName}</h2><p>Kale Sv.{lv} · {game.buildings.length} yapı · {Object.values(game.units).reduce((a,b)=>a+b,0)} asker</p><small>{(terrainCatalog[game.terrain]??terrainCatalog.plain).bonus} · {otherKingdoms.length} komşu sancak genel haritada</small></div>{game.queue&&<div className="active-queue"><span>{game.queue.kind==="building"?"⚒ HARİTADA İNŞAAT":"EĞİTİM DEVAM EDİYOR"}</span><b>{game.queue.name}</b><strong>{left(game.queue.completesAt,now)}</strong><div className="queue-progress"><i style={{width:`${game.queue.startedAt?Math.max(4,Math.min(100,(now-game.queue.startedAt)/(game.queue.completesAt-game.queue.startedAt)*100)):8}%`}}/></div></div>}
 <aside className="council-panel"><div className="general-bars">{[["Sadakat",game.loyalty],["Emir Kotası",`${game.quota}/${qph(lv)*2}`],["İtibar",game.reputation]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><div><i style={{width:`${typeof value==="number"?value:game.quota/(qph(lv)*2)*100}%`}}/></div><b>{value}</b></div>)}</div><nav className="tabs five">{(["meclis","binalar","ordu","defter","diyar"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.toLocaleUpperCase("tr")}</button>)}</nav><div className="panel-content">
 {tab==="meclis"&&<div className="council-content"><div className="advisor"><div className="portrait">A</div><div><h3>{game.generalConnected?"General Aldric":"General sessiz"}</h3><p>{game.generalConnected?`${game.provider} · ${game.model}`:"BYOK bağlantısı bekleniyor"}</p></div>{!game.generalConnected&&<button className="reconnect-button" onClick={()=>{setGeneralError("");setShowConnect(true)}}>BAĞLA</button>}<span className={game.generalConnected?"online":"offline"}>●</span></div><div className="first-objective"><span>İLK HEDEF</span><b>Ekonomiyi dengede tut</b><p>Yiyecek üretimini pozitif tutun; ardından Meydan veya Kışla kurun.</p></div><div className="general-authority"><span>GENERALİN AKTİF YETKİLERİ</span><div><i>Yapı kur/yükselt</i><i>İnşaat hızlandır</i><i>Birlik eğit</i><i>Vergi ayarla</i><i>Şenlik düzenle</i><i>Doktrin kaydet</i><i>Madene işçi gönder</i><i>İşçileri geri çek</i><i>Ajan gönder</i><i>Karşı-istihbarat kur</i></div><small>Rutin emirleri doğrudan uygular; kaynak, kota veya halk riski varsa engeller ya da teyit ister.</small></div><div className="chat-log">{chat.map((x,i)=><div className={x.who===game.rulerName?"message king":"message"} key={i}><b>{x.who}</b><RichMessage text={x.text}/></div>)}{connecting&&<div className="message thinking"><b>GENERAL ALDRIC</b><p>Haritayı ve defterleri inceliyor…</p></div>}</div><form className="chat-form" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Generalinize buyruğunuzu iletin…" disabled={connecting}/><button disabled={connecting}>✦</button></form></div>}
 {tab==="binalar"&&<div className="list-content"><div className="section-head"><span>{game.buildings.length} / {6+(lv-1)*2} YAPI · RAPOR</span><b>{game.queue?.kind==="building"?"1 kuyrukta":"General planlayabilir"}</b></div><div className="general-only-note"><b>Binaları General yönetir</b><span>Bir hedef ver veya onu ikna et: “Önce yiyeceği güvenceye al, sonra Meydan kur.”</span></div><button className="keep-card" disabled={lv>=6||connecting} onClick={()=>void submitOrder(`Kale yapısını Sv.${lv+1} seviyesine yükselt.`)}><span>♜</span><div><b>Kale Sv.{lv}{lv<6?` · sıradaki ${lv+1}`:" · Tavan"}</b><small>İdari kapasite ve emir kotası</small></div><strong>{lv>=6?"TAVAN":"EMİR VER"}</strong></button>{catalog.map(item=>{const current=game.buildings.find(b=>b.type===item.type)?.level??0,locked=item.unlock>lv,cost=costFor(item.cost,current);return <button className={`build-action ${locked?"locked":""}`} disabled={locked||connecting} onClick={()=>void submitOrder(current?`${item.name} yapısını Sv.${current+1} seviyesine yükselt.`:`${item.name} yapısını kur.`)} key={item.type}><span>{item.category}</span><div><b>{item.name} {current?`Sv.${current}`:"Kurulmadı"}</b><small>{locked?`Kale Sv.${item.unlock} gerekli`:item.detail}</small><em>Sonraki emir maliyeti · {Object.entries(cost).map(([k,v])=>`${k} ${v}`).join(" · ")}</em></div><strong>{locked?"KİLİTLİ":"EMİR VER"}</strong></button>})}</div>}
 {tab==="ordu"&&<div className="army-panel"><div className="section-head"><span>GARNİZON · RAPOR</span><b>{game.units.spearman??0} asker</b></div><div className="general-only-note"><b>Orduyu General yönetir</b><span>Kaç asker istediğini veya savunma hedefini söyle. General nüfus ve yiyecek riski varsa itiraz eder.</span></div><div className="empty-army"><span>⚔</span><h3>{game.buildings.some(b=>b.type==="barracks")?"Kışla Generalin emrini bekliyor":"Henüz Kışlanız yok"}</h3><p>{game.buildings.some(b=>b.type==="barracks")?"Mızrakçı başına: 8 altın · 10 yiyecek · 1 demir":"Kışla kurulması için General'e stratejik gerekçeni ilet."}</p></div><div className="unit-row"><span>Mızrakçı</span><b>{game.units.spearman??0}</b><small>Savunma 16 · Hız 6</small></div></div>}
 {tab==="defter"&&<div className="ledger"><div className="section-head"><span>HAZİNE VE HALK · RAPOR</span><b>Tick canlı</b></div><div className="general-only-note"><b>Defter karar değil, istihbarattır</b><span>Vergi ve şenlik kararlarını General'e bildir; halkın rızasına göre uygulayabilir veya karşı çıkabilir.</span></div>{meta.map(([k,label])=><div key={k}><span>{label}</span><strong>{fmt(game.resources[k])}</strong><small className={(rt?.[k]??0)<0?"negative":""}>{(rt?.[k]??0).toFixed(1)}/sa</small></div>)}<div className="tax-control"><label>Mevcut vergi oranı <b>%{game.taxRate}</b></label><input type="range" min="0" max="50" value={game.taxRate} disabled/><small>Değiştirmek için General'i ikna etmelisin.</small></div></div>}
 {tab==="diyar"&&<div className="realm"><div className="section-head"><span>DIŞ ÇEPER · KORUMALI</span><b>{left(game.protectionEndsAt,now)}</b></div><div className={`terrain-summary ${game.terrain}`}><span>BAŞKENT ARAZİSİ</span><b>{(terrainCatalog[game.terrain]??terrainCatalog.plain).label}</b><p>{(terrainCatalog[game.terrain]??terrainCatalog.plain).description}</p><small>{(terrainCatalog[game.terrain]??terrainCatalog.plain).bonus}</small></div><div className="world-intel"><div className="intel-defense"><div><b>KARŞI-İSTİHBARAT</b><span>{worldDefense.active?`Nöbet etkin · ${left(worldDefense.activeUntil??now,now)}`:"Ajan savunması kapalı"}</span>{incomingAlerts>0&&<em>{incomingAlerts} düşman ajanı tespit edildi</em>}</div><button disabled={worldBusy||worldDefense.active} onClick={()=>void worldAction("defend")}>{worldDefense.active?"NÖBETTE":"NÖBET KUR"}</button></div>{sharedMine&&<div className="shared-mine"><span>⛏ CHANNEL ORTAK SAHASI</span><b>{sharedMine.mine.name}</b><small>{fmt(sharedMine.mine.extractedOre)} cevher çıkarıldı · {fmt(sharedMine.mine.oreRemaining)} kaldı · {sharedMine.mine.totalWorkers} işçi</small><div>{sharedMine.participants.map(worker=><i key={worker.id}>{worker.name} · {worker.workers}</i>)}</div><button disabled={worldBusy} onClick={()=>void mineAction(sharedMine.participants.some(worker=>worker.self)?"leave":"join")}>{sharedMine.participants.some(worker=>worker.self)?"İŞÇİLERİ ÇEK":"5 İŞÇİ GÖNDER"}</button></div>}<div className="world-kingdoms"><div className="section-head"><span>AYNI CHANNEL · {otherKingdoms.length} SANCAK</span><b>İsimler keşifle açılır</b></div>{otherKingdoms.length===0?<p className="empty-world">Bu channel&apos;da henüz başka bir krallık yok.</p>:otherKingdoms.map(kingdom=><article className={kingdom.discovered?"kingdom-contact discovered":"kingdom-contact"} key={kingdom.id}><div><b>{kingdom.name??"Bilinmeyen Sancak"}</b><span>{terrainCatalog[kingdom.terrain as TerrainId]?.label??"BİLİNMEYEN BÖLGE"} · Haritada ({kingdom.position.x}, {kingdom.position.z})</span></div>{kingdom.report?<small>Kale Sv.{kingdom.report.keepLevel} · {kingdom.report.population} nüfus · {kingdom.report.army} asker · {kingdom.report.buildingCount} yapı</small>:kingdom.mission?.status==="pending"?<small>Ajan yolda · {left(kingdom.mission.completesAt,now)} · başarı %{kingdom.mission.successChance}</small>:<small>İçerik gizli · keşif başarı ihtimali düşük</small>}<button disabled={worldBusy||kingdom.mission?.status==="pending"} onClick={()=>void worldAction("scout",kingdom.id)}>{kingdom.mission?.status==="pending"?"AJAN YOLDA":kingdom.discovered?"YENİDEN KEŞFET":"AJAN GÖNDER"}</button></article>)}</div></div>{game.notices.map((x,i)=><div className="report" key={i}><span>{x.kind}</span><p>{x.text}<small>{new Date(x.at).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})}</small></p></div>)}</div>}
 </div></aside>{worldView&&<ChannelWorldMap channelName={game.channel} homeName={game.kingdomName} homeTerrain={game.terrain} kingdoms={otherKingdoms} sharedMine={sharedMine} busy={worldBusy} formatLeft={at=>left(at,now)} onClose={()=>setWorldView(false)} onScout={id=>void worldAction("scout",id)} onMine={action=>void mineAction(action)}/>} {tutorialStep!==null&&<Tutorial step={tutorialStep} next={advanceTutorial} skip={closeTutorial}/>}</section></main>
}

const tutorial=[
 {eyebrow:"I · YENİ KRALLIK",title:"Önce başkentini ve arazini tanı",text:"Sv.1 ahşap kalen, üç başlangıç yapın ve dört günlük koruman var. Seçtiğin arazi haritanın coğrafyasını, üretim hızını ve savunmanı kalıcı olarak etkiler. Haritayı sürükleyerek döndür, tekerlekle yakınlaş."},
 {eyebrow:"II · MECLİS",title:"Generalini yönlendir ve ikna et",text:"Sen Kral olarak hedef ve gerekçe verirsin; General kaynakları, halkı, sadakatini ve yönetim doktrinini tartıp ayrıntıları kendisi yönetir. Riskli emirde itiraz edebilir."},
 {eyebrow:"III · BİNALAR",title:"Raporu oku, emri General'e ver",text:"Binalar sekmesi salt okunur bir durum raporudur. İnşa ve yükseltme için Meclis'te doğal dille emir ver; General uygun bulursa kuyruğu başlatır."},
 {eyebrow:"IV · DEFTER",title:"Karar için istihbarat topla",text:"Defterde saatlik değerleri izlersin fakat vergiyi düğmeyle değiştirmezsin. General'i rakamlar ve gerekçelerle ikna etmelisin."},
 {eyebrow:"V · DİYAR",title:"Koruma bitmeden hazırlan",text:"Dış dünya ilerledikçe açılır. Önce ekonomi ve kışla, sonra diplomasi ve fetih. Krallığın hesabına otomatik kaydedilir."},
];
function Tutorial({step,next,skip}:{step:number;next:()=>void;skip:()=>void}){const item=tutorial[step];return <div className="tutorial-layer"><section className="tutorial-card"><div className="tutorial-progress">{tutorial.map((_,i)=><i className={i<=step?"done":""} key={i}/>)}</div><p>{item.eyebrow}</p><h3>{item.title}</h3><span>{item.text}</span><div><button onClick={skip}>REHBERİ GEÇ</button><button className="primary-seal" onClick={next}>{step===tutorial.length-1?"OYUNA BAŞLA":"SONRAKİ"}</button></div></section></div>}

function Onboarding(p:{channels:Channel[];step:Setup;setStep:(s:Setup)=>void;selected:Channel;setSelected:(c:Channel)=>void;name:string;setName:(s:string)=>void;ruler:string;setRuler:(s:string)=>void;terrain:TerrainId;setTerrain:(s:TerrainId)=>void;provider:keyof typeof modelOptions;setProvider:(s:keyof typeof modelOptions)=>void;model:string;setModel:(s:string)=>void;apiKey:string;setApiKey:(s:string)=>void;found:(c:boolean)=>void;connect:()=>void;connecting:boolean;error:string}){return <main className="onboarding"><div className="onboarding-bg"><div className="distant-castle">♜</div></div><header className="onboarding-header"><div className="brand-mark">♜</div><div className="title-block"><h1>DEMİRKALE</h1><p>KRALLIK SİMÜLASYONU</p></div><span>KALICI DÜNYA · BYOK GENERAL</span></header>
 {p.step==="welcome"&&<section className="welcome-card"><p className="eyebrow">TAHT BOŞ · DİYAR SENİ BEKLİYOR</p><h2>Bir krallık miras almayacaksın.<br/><em>Onu sıfırdan kuracaksın.</em></h2><p>Boş bir dış çeper parseli, Kale Sv.1, yüz kişilik bir halk ve sınırlı erzak. Generalinize yön verin; ekonomi, diplomasi ve savaş siz çevrimdışıyken de yaşamaya devam etsin.</p><div className="starting-ledger"><span>1 Kale</span><span>100 Halk</span><span>1.000 Altın</span><span>4 Gün Koruma</span></div><button className="primary-seal" onClick={()=>p.setStep("channel")}>TAHTA DOĞRU İLERLE</button><small>Krallığın hesabına otomatik kaydedilir; başka bir tarayıcıdan kaldığın yerden devam edebilirsin.</small></section>}
 {p.step==="channel"&&<section className="setup-card"><div className="step-count">I / III</div><p className="eyebrow">BİR DÜNYA SEÇ</p><h2>Hangi channel&apos;da hüküm süreceksin?</h2><p>Her channel ayrı bir krallık ve ayrı bir sezondur. Yalnızca yönetimin aktif tuttuğu dünyalar listelenir.</p><div className="channel-list">{p.channels.map(c=><button key={c.id} className={p.selected.id===c.id?"selected":""} onClick={()=>p.setSelected(c)}><i>♜</i><div><b>{c.name}</b><span>{c.detail}</span></div><strong>{c.remaining}</strong></button>)}</div><div className="setup-actions"><button onClick={()=>p.setStep("welcome")}>GERİ</button><button className="primary-seal" disabled={!p.selected} onClick={()=>p.setStep("kingdom")}>BU DÜNYAYA KATIL</button></div></section>}
 {p.step==="kingdom"&&<section className="setup-card"><div className="step-count">II / III</div><p className="eyebrow">SANCAĞINI DİK</p><h2>Krallığını kur</h2><div className="form-grid"><label>Hükümdarın adı<input value={p.ruler} onChange={e=>p.setRuler(e.target.value)} placeholder="Örn. Alaric" maxLength={30}/></label><label>Krallığın adı<input value={p.name} onChange={e=>p.setName(e.target.value)} placeholder="Örn. Demirkale" maxLength={36}/></label></div><p className="field-label">Başlangıç arazisi — görünüşü ve üretimi kalıcı olarak değiştirir</p><div className="terrain-list">{(Object.entries(terrainCatalog) as Array<[TerrainId,(typeof terrainCatalog)[TerrainId]]>).map(([id,item])=><button key={id} className={p.terrain===id?`selected ${id}`:id} onClick={()=>p.setTerrain(id)}><b>{item.label}</b><span>{item.bonus}</span></button>)}</div><div className="terrain-choice-detail"><b>{terrainCatalog[p.terrain].description}</b><span>{terrainCatalog[p.terrain].bonus}</span></div><div className="setup-actions"><button onClick={()=>p.setStep("channel")}>GERİ</button><button className="primary-seal" disabled={!p.name.trim()||!p.ruler.trim()} onClick={()=>p.setStep("general")}>PARSELİ TAHSİS ET</button></div></section>}
 {p.step==="general"&&<section className="setup-card"><div className="step-count">III / III</div><p className="eyebrow">GENERALİNİ UYANDIR</p><h2>BYOK modelini bağla</h2><p>Anahtarınız hesabınıza AES-GCM ile şifreli kaydedilir; tarayıcıya geri gönderilmez ve yalnızca seçtiğiniz sağlayıcıya istek yapılırken sunucuda çözülür.</p><div className="form-grid"><label>Sağlayıcı<select value={p.provider} onChange={e=>{const next=e.target.value as keyof typeof modelOptions;p.setProvider(next);p.setModel(modelOptions[next][0].id)}}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label><label>Model<select value={p.model} onChange={e=>p.setModel(e.target.value)}>{modelOptions[p.provider].map(option=><option value={option.id} key={option.id}>{option.label}</option>)}</select></label><label className="wide">API anahtarı<input type="password" value={p.apiKey} onChange={e=>p.setApiKey(e.target.value)} placeholder="Bağlanırken gerçek sağlayıcı isteğiyle doğrulanır" autoComplete="off"/></label></div>{p.error&&<div className="connection-error">{p.error}</div>}<div className="key-warning">Bağlantı bu hesapta kalıcıdır. Başka bir tarayıcıdan giriş yaptığınızda General otomatik olarak aynı sağlayıcı ve modelle bağlanır.</div><div className="setup-actions"><button onClick={()=>p.setStep("kingdom")}>GERİ</button><button onClick={()=>p.found(false)}>GENERAL SESSİZKEN BAŞLA</button><button className="primary-seal" disabled={p.connecting||!p.apiKey.trim()} onClick={p.connect}>{p.connecting?"DOĞRULANIYOR…":"GENERALİ BAĞLA VE TAHTA ÇIK"}</button></div></section>}
 </main>}
