export const GENERAL_TOOLS=[
  {name:"build_structure",description:"Yeni bina kurar veya yükseltir.",parameters:{type:"object",properties:{building_type:{type:"string"},target_level:{type:"integer"}},required:["building_type","target_level"]}},
  {name:"train_unit",description:"Birim eğitim kuyruğu oluşturur.",parameters:{type:"object",properties:{unit_type:{type:"string"},count:{type:"integer"}},required:["unit_type","count"]}},
  {name:"move_army",description:"Orduyu saldırı, takviye, keşif veya akına yollar.",parameters:{type:"object",properties:{target_x:{type:"integer"},target_y:{type:"integer"},intent:{enum:["attack","reinforce","scout","raid"]},composition:{type:"object"}},required:["target_x","target_y","intent","composition"]}},
  {name:"send_caravan",description:"En çok 200 kaynağı kervanla taşır.",parameters:{type:"object",properties:{origin_tile_id:{type:"string"},target_tile_id:{type:"string"},resource_type:{type:"string"},amount:{type:"number"}},required:["origin_tile_id","target_tile_id","resource_type"]}},
  {name:"host_festival",description:"Yiyecek, bira ve altınla şenlik düzenler.",parameters:{type:"object",properties:{}}},
  {name:"set_tax_rate",description:"Vergi oranını ayarlar.",parameters:{type:"object",properties:{rate_percent:{type:"integer",minimum:0,maximum:100}},required:["rate_percent"]}},
  {name:"send_diplomacy_message",description:"Karşı krallığın Generaline teklif yollar; Kral karşı tarafa doğrudan yazamaz.",parameters:{type:"object",properties:{target_kingdom_id:{type:"string"},message:{type:"string"},proposal_type:{enum:["ceasefire","alliance","trade","protection_offer","vassalage_request","betrayal_signal"]}},required:["target_kingdom_id","message","proposal_type"]}},
  {name:"post_market_offer",description:"Anonim pazar ilanı yayınlar.",parameters:{type:"object",properties:{offer_resource:{type:"string"},offer_amount:{type:"number"},request_resource:{type:"string"},request_amount:{type:"number"}},required:["offer_resource","offer_amount","request_resource","request_amount"]}},
  {name:"accept_market_offer",description:"Pazar ilanını kervan teslimatıyla kabul eder.",parameters:{type:"object",properties:{offer_id:{type:"string"}},required:["offer_id"]}},
  {name:"propose_troop_rental",description:"Sadece savunmada kullanılabilen temel birlik kiralama teklifi yapar.",parameters:{type:"object",properties:{target_kingdom_id:{type:"string"},unit_type:{type:"string"},count:{type:"integer"},duration_days:{enum:[3,7,14]},fee_gold:{type:"integer"}},required:["target_kingdom_id","unit_type","count","duration_days","fee_gold"]}},
  {name:"deploy_spy",description:"Bilgi veya sabotaj için casus yollar.",parameters:{type:"object",properties:{target_kingdom_id:{type:"string"},mission:{enum:["gather_intel","sabotage"]}},required:["target_kingdom_id","mission"]}},
] as const;
