import { KEEP_LEVELS, TERRAIN, UNIT, type Composition, type UnitType } from "./catalog.js";
export type ResourceBag=Record<string,number>;
export const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
export function quotaForKeep(level:number){return KEEP_LEVELS[clamp(Math.floor(level),1,6) as keyof typeof KEEP_LEVELS].quota;}
export function refillQuota(current:number,lastRefill:Date,now:Date,keepLevel:number){const hourly=quotaForKeep(keepLevel),hours=Math.floor((now.getTime()-lastRefill.getTime())/3_600_000);return {remaining:clamp(current+hours*hourly,0,hourly*2),refilledAt:hours?new Date(lastRefill.getTime()+hours*3_600_000):lastRefill};}
export function mineMultiplier(remaining:number,original:number){if(original<=0||remaining<=0)return 0;const ratio=remaining/original;return ratio>=.2?1:ratio/.2;}
export function deepDigCost(count:number){return Math.round(500*Math.pow(1.5,count));}
export function populationDelta(popularity:number,foodSurplusPerHour:number,squareLevel:number,hours:number){const consent=(popularity-50)/50,food=clamp(foodSurplusPerHour/100,-1,1);return (consent*.55+food*.35+squareLevel*.12)*hours;}
export function popularityDelta(args:{taxRate:number;foodBalance:number;ale:number;cheese:number;churchLevel:number;losses:number;festivalBonus?:number}){return clamp((15-args.taxRate)*.04+clamp(args.foodBalance/100,-1,1)*.5+Math.min(args.ale/100,.3)+Math.min(args.cheese/100,.15)+args.churchLevel*.08-args.losses*.4+(args.festivalBonus??0),-4,4);}
export function festivalBoost(festivalsThisWeek:number){return 12*Math.pow(.55,festivalsThisWeek);}
export function travelHours(distance:number,composition:Composition,terrain:keyof typeof TERRAIN){const speeds=Object.entries(composition).filter(([,n])=>(n??0)>0).map(([u])=>UNIT[u as UnitType].speed);const slowest=speeds.length?Math.min(...speeds):4;return distance/(slowest*TERRAIN[terrain].speed);}
export function fatigue(distance:number){return clamp(1-Math.max(0,distance-12)*.012,.55,1);}
export function armyPower(composition:Composition,mode:"attack"|"defense"){return Object.entries(composition).reduce((sum,[type,count])=>sum+(UNIT[type as UnitType][mode]??0)*(count??0),0);}
export function resolveRaid(args:{attackers:Composition;defenders:Composition;terrain:keyof typeof TERRAIN;attackerMorale:number;defenderMorale:number;fatigue:number;tacticAttack:number;tacticDefense:number;keepLevel:number;wallLevel:number;towerLevel:number;seed:number}){const ap=armyPower(args.attackers,"attack")*args.attackerMorale*args.fatigue*args.tacticAttack*(.9+args.seed*.2);const fort=(args.keepLevel*args.wallLevel*Math.max(1,args.towerLevel))*18;const dp=(armyPower(args.defenders,"defense")*args.defenderMorale*args.tacticDefense*TERRAIN[args.terrain].defense+fort)*(1.1-args.seed*.2);const attackerWins=ap>dp;const ratio=Math.min(ap,dp)/Math.max(ap,dp,1);return{attackerWins,attackPower:Math.round(ap),defensePower:Math.round(dp),attackerLossRate:clamp((attackerWins?.18:.48)*ratio+.08,.08,.75),defenderLossRate:clamp((attackerWins?.5:.2)*ratio+.06,.06,.8)};}
export function siegeRound(args:{attackers:Composition;defenders:Composition;wallIntegrity:number;terrain:keyof typeof TERRAIN;moraleA:number;moraleD:number;fatigue:number;keep:number;wall:number;tower:number;seed:number}){const battle=resolveRaid({attackers:args.attackers,defenders:args.defenders,terrain:args.terrain,attackerMorale:args.moraleA,defenderMorale:args.moraleD,fatigue:args.fatigue,tacticAttack:1,tacticDefense:1,keepLevel:args.keep,wallLevel:args.wall,towerLevel:args.tower,seed:args.seed});const siege=Object.entries(args.attackers).reduce((n,[u,c])=>n+((UNIT[u as UnitType] as {siege?:number}).siege??0)*(c??0),0);const wallDamage=clamp(siege/Math.max(15,args.wall*30)*(battle.attackerWins?1.15:.65),0,35);const integrity=clamp(args.wallIntegrity-wallDamage,0,100);return{...battle,wallDamage,wallIntegrity:integrity,finished:integrity<=0&&battle.attackerWins};}
export function transferResources(bag:ResourceBag,resource:string,requested:number,capacity=200){const amount=Math.max(0,Math.min(requested,capacity,bag[resource]??0));return{amount,remaining:{...bag,[resource]:(bag[resource]??0)-amount}};}
